- README.md
> It is not necessary to notify the mailing list for editorial issues.
:sunglasses:
> fix "contributing" link in readme

- draft-ietf-httpbis-tunnel-protocol.xml
This adds a section regarding falsification of Tunnel-Protocol.  I didn't expand this to note that WebRTC won't suffer from this problem because the application won't be able to set the header field.  That seemed like too much detail.
> Falsification

- draft-ietf-httpbis-tunnel-protocol.xml
Last call discussion identified this as a solution to the confusion that exists around the intent of the header field.
Closes #57.
> Renaming to ALPN

- draft-ietf-httpbis-http2-encryption.md
* consistent use of `http` instead of "http"
* make S1.1, P3 a bit more readable
> editorial changes

- draft-ietf-httpbis-alt-svc.xml
An alternate can send an Alt-Svc field that overrides that sent by the origin and is cached on an equal basis.
> Issue 74:  Alternates are authoritative

- .gitignore
- Makefile
- README.md
- draft-ietf-httpbis-encryption-encoding.md
Need to check that this is OK first.
> Merge encryption

- draft-ietf-httpbis-encryption-encoding.md
This is a proposal to address issue #135
/cc @martinthomson
> Use two octets to indicate record padding length in httpbis-encryption-encoding

- draft-ietf-httpbis-encryption-encoding.md
In order to allow existing applications to update from one octet of
padding per record to two (PR #136, Issue #135), this PR renames
"aesgcm128" to "aesgcm" as the value for the Content-Encoding header,
as well as the parameter name in the Crypto-Key header.
This also affects the context used for deriving the nonce and the
content encryption key. Examples have been updated.
What I did not update is the JWE mapping (currently "A128GCM"). Do
we wish to change that to "AGCM", which may be less descriptive?
> Rename aesgcm128 to aesgcm to provide an update path

- draft-ietf-httpbis-http2-encryption.md
Second round on this one, small tweaks and a small amount of restructuring.
> Refining the framing of the commitment

- draft-ietf-httpbis-client-hints.md
https://lists.w3.org/Archives/Public/ietf-http-wg/2016JanMar/0519.html
Outstanding issues:
> WIP: addressing CH feedback

- draft-ietf-httpbis-origin-frame.md
Putting the meat of the document in Section 1.2 was a bit odd.  Also, the fields descriptions were glommed together.
> Fix formatting

- draft-ietf-httpbis-http2-encryption.md
We make this decision explicitly, and we don't want to imply that just because you don't have a fresh "http-opportunistic" resource, any commitment is shortened as a result (which is a reasonable interpretation based on the current text).
> Commitment might exceed the freshness lifetime

- draft-ietf-httpbis-client-hints.md
- only one "on" value is recognized today
- allow parameters on token
Discussion: https://github.com/httpwg/http-extensions/issues/168
@mnot @reschke can you please do a quick sanity check?
> make Save-Data extensible

- draft-ietf-httpbis-encryption-encoding.md
> PHK's keyid changes

- draft-ietf-httpbis-http2-encryption.md
The key phrase is "Serving ... requires", not "URIs require".
> Subject-verb agreement

- draft-ietf-httpbis-http2-encryption.md
We've been circling an answer to this for a while.  The entire gamut of possible solutions is broad, and we haven't had much luck in reaching clarity here.
One the one end of the scale, it should be perfectly OK to send a request for an `http` origin over an authenticated TLS connection.  But we still have the (entirely legitimate) concern there is that some servers might get themselves confused by this.
The other end of the scale is the bells and whistles JSON stuff.  @mcmanus seemed OK with this based on his implementation experience, but it is a little complicated.  We found too many corner cases for me to be happy that it implementations wouldn't end up busted.  And now that we insist on authentication for the server, many of the features didn't make sense.
We've also considered an …
> Simplify opportunistic encryption

- draft-ietf-httpbis-encryption-encoding.md
This moves the values that were in the Encryption header field to
the start of the payload.  This provides a meagre efficiency gain
as well as removing the need to have two correlated header fields.
This should go most of the way to address WGLC comments.
> Remove Encryption header field

- draft-ietf-httpbis-http2-encryption.md
I tried to make this work, but @mcmanus is right: this is entirely a transport decision and given that our best option was to violate a MUST in RFC 7230, that's too hard.  This just says that HTTP/1.1 is no good because we can't include the scheme (because RFC 7230 says we can't).  I almost made this h2-specific, but then remembered that there might be another protocol that has favourable properties.
> Exclude HTTP/1.1

- draft-ietf-httpbis-http2-encryption.md
This is kinda silly, but it seems like adding support for coalescing is
something we could fix later.
Closes #269 with the nuclear option.
> Don't allow clients to send http and https requests coalesced.

- draft-ietf-httpbis-cache-digest.md
I think this is correct, since it doesn't quite seem to make sense otherwise.
> fix typo bit -> be

- draft-ietf-httpbis-encryption-encoding.md
Following the discussion on the list.
> Move to using padding that is more like TLS

- draft-ietf-httpbis-origin-frame.md
- writeups/5987bis.md
- Relax DNS requirements when ORIGIN is received
- Change the initial origin set to just SNI
> DNS relaxation, smaller initial Origin Set

- draft-ietf-httpbis-client-hints.md
> define Accept-CH-Lifetime

- draft-ietf-httpbis-origin-frame.md
While testing firefox's implementation of this draft Vlad determined that some versions of Chrome throw PROTOCOL_ERROR and close the connection if it receives a type 0xB frame with a non zero length on stream 0.
Other frame type numbers, such as 0xC do not seem to have that problem.
testing indicates this is fixed in version 59 and is a problem previous to that. (57 is in release as I write this).
presumably this is related to historical code around BLOCKED which was proposed to use 0xB.
Prudence says to just use a different code point for the moment.
> change frame type of origin to 0xc to avoid conflict

- draft-ietf-httpbis-expect-ct.md
This changes Expect-CT to be a comma-separated list of directives (which may be
name=value pairs), and adds some examples.
Also allows the server to send multiple header fields so that they can be
combined, as per
https://github.com/httpwg/http-extensions/issues/318#issuecomment-294369176
Fixes issue #318, #321
> Update Expect-CT syntax to match convention

- draft-ietf-httpbis-origin-frame.md
1. Fix one typo.
2. Technically, a set is always a subset of itself.  Therefore current wording implies that if two connections have identical Origin Sets, then neither should be used for new requests, and both should be closed.  Fix this by saying "proper subset" instead of "subset".
> Two editorial nits.

- draft-ietf-httpbis-cache-digest.md
#256.
Since I wasn't sure if we can make normative references from an appendix, RFC5234 (ABNF) and RFC4648 (Base64) has been added as informative references.
> define `cache-digest` header in appendix

- draft-ietf-httpbis-cache-digest.md
The header needs to be registered if it's going to appear in an RFC.
Looking at 7540, I think the frame type needs to be registered as well, since "Experimental Use" is private / local only.
> Register header, frame type with IANA

- draft-ietf-httpbis-early-hints.md
Adds an example showing how 103 can be used.
> add example

- draft-ietf-httpbis-early-hints.md
based on the suggestion in https://lists.w3.org/Archives/Public/ietf-http-wg/2017AprJun/0147.html
> adjust the explanation why it is difficult to generate the header block of a final response immediately

- draft-ietf-httpbis-early-hints.md
This is a PR that essentially rebases the change proposed in #319.
To me the change proposed by @royfielding is a clear improvement. I believe that we should merge this.
> improve the wording: "client MUST NOT process" 

- draft-ietf-httpbis-early-hints.md
* removes statements that are either redundant or contradicts with RFC 7230, 7231
* clarifies how a server is expected to do when generating a response
> fix contradictory definintions with HTTP/1.1

- draft-ietf-httpbis-origin-frame.md
Make optionallity more like ALTSVC, make test less Gollum-like
> ORIGIN frame typos

- draft-ietf-httpbis-client-hints.md
See https://github.com/httpwg/http-extensions/issues/359, https://github.com/httpwg/http-extensions/issues/360.
> Address client-hints-04 feedback

- draft-ietf-httpbis-origin-frame.md
The consequences for ORIGIN + Alt-Svc with a port change aren't awesome, but this should at least remove any confusion.
> Explain interactions with Alt-Svc

- draft-ietf-httpbis-early-hints.md
following the discussion on [this thread](https://lists.w3.org/Archives/Public/ietf-http-wg/2017JulSep/0164.html)
> better clarify the differences between H2 server push

- draft-ietf-httpbis-early-hints.md
Clarify that the disappearance of a header field (that once existed in a 103 response) from the following 103 responses does not indicate the retraction of the expectation that the header field will be included in the final response.
closes #371
> clarify multi-103 behavior

- draft-ietf-httpbis-replay.md
@mcmanus was confused by the text here and I confess that I don't remember why
it was added.  There are actually esoteric cases where you get server data that
you can read before the handshake is complete (QUIC tends to enable that sort
of mess), but there is no circumstance where the client can read the 425 but
can't also determine whether that the handshake is not done to its
satisfaction.  The client might decide that it wants to abort and not provide a
certificate or something, but most implementations don't really allow that sort
of messing around.
> You can't actually receive a 425 if the handshake doesn't complete

- draft-ietf-httpbis-replay.md
This text from Kyle Rose highlights the decision process.  If any node might
make a different decision about processing early data, then *this* node has to
wait.
> Be extra consistent

- draft-ietf-httpbis-replay.md
The best and easiest plan is to discard, but we know that throwing out
perfectly good packets can have bad effects on performance.  It sends a bad
signal to a congestion controller for instance.  So we need to say either
discard, or ensure that the data is properly attributed and consistently
processed.
Closes #391.
> Manage out of order early data delivery

- draft-ietf-httpbis-expect-ct.md
Make references consistent (both within the doc and across WG documents)
> reference format

- draft-ietf-httpbis-rand-access-live.xml
- mention the syntax
- update the reference
- type the citations consistently
> tune use of ABNF (closes #415)

- draft-ietf-httpbis-replay.md
This makes mitigation mandatory.  Either receive a signal that early data is safe for the given resource, or apply the mitigations.  That's consistent with the other text.
> Be more definite about early data

- draft-ietf-httpbis-replay.md
I think that these are the main places where we weren't clear enough about the relevant TLS role.
> Clarify intermediary TLS role better

- draft-ietf-httpbis-replay.md
Hopefully none of this collides with other PRs in flight.
> Nits from Ben Kaduk's review

- draft-ietf-httpbis-rand-access-live.xml
- add type
- consistently indent
- trailing lines for requests
- add mandatory Host header fields
> Tune HTTP examples

- draft-ietf-httpbis-bcp56bis.md
remove "various" as authors, just list the org, remove misleading date
> remove misleading WHATWG info

- Makefile
- draft-ietf-httpbis-bcp56bis.md
- draft-ietf-httpbis-cache-digest.md
- draft-ietf-httpbis-client-hints.md
- draft-ietf-httpbis-early-hints.md
- draft-ietf-httpbis-expect-ct.md
- draft-ietf-httpbis-h2-websockets.md
- draft-ietf-httpbis-header-structure.md
- draft-ietf-httpbis-key.md
- draft-ietf-httpbis-origin-frame.md
- draft-ietf-httpbis-rfc6265bis.md
Uses the added feature in https://github.com/martinthomson/i-d-template/pull/129 to drop shortname copies of the drafts in gh-pages to fix the broken links.  These are actual copies, not symlinks, but git keeps those relatively cheap.
Shouldn't break anything to have in the Makefile without that change, either.
> Shortnames in gh-pages

- draft-ietf-httpbis-rfc6265bis.md
I left the term "request-uri" untouched (it was renamed in the base spec because it's not always a URI). We may want to change that separately, or even refer to the effective request URI (https://www.greenbytes.de/tech/webdav/rfc7230.html#effective.request.uri)
> RFC 2616 -> 723x

- draft-ietf-httpbis-h2-websockets.md
* Add SETTINGS_ prefix to parameter name ENABLE_CONNECT_PROTOCOL.
* Fix one typo ("s/a entry/an entry/").
* Remove "(type = 0x8)" which is ambigous (what is type?) and redundant
with code listed in IANA Considerations section.
> Add SETTINGS_ prefix to parameter name.

- draft-ietf-httpbis-http2-secondary-certs.md
Tracking changes from tlswg/tls-exported-authenticator#9 to create an exported authenticator request message at the TLS layer as well.
This is a straight port of https://github.com/MikeBishop/http2-certs/pull/18/; feedback there has already been addressed, modulo one issue I'll be adding to this repo.
> Incorporate exported authenticator requests

- draft-ietf-httpbis-bcp56bis.md
Port over of PR from mnot repo. Modified last sentence to avoid to much usage of the word "further".
> bcp56bis: Status code reason phrase

- draft-ietf-httpbis-cache-digest.md
Resolves https://github.com/httpwg/http-extensions/issues/268
> Switch digest to cuckoo filters, to enable O(1) removal

- draft-ietf-httpbis-bcp56bis.md
Mention obsoletion in the abstract, tune section title in appendix, and actually cite RFC 3205.
> bcp56bis: RFC 3205 ref

- draft-ietf-httpbis-bcp56bis.md
FWIW, it might also be good not to have kramdown-specific syntax here...
> bcp56bis: avoid overlong artwork line

- draft-ietf-httpbis-header-structure.md
Since be5ab4c153be0a10d301d7d55c425a5025b1ab40 required it.
I'd probably have kept padding forbidden to save a couple bytes here and there, and made Python folks append the right number of `=`s, but whatever.
> Use the right amount of base64 padding in binary content examples.

- draft-ietf-httpbis-header-structure.md
- underscores
- case insensitivity (char vs CHAR)
- also attempts to clarify ch(a)r / unescaped production a bit
> fix ABNF (see #520)

- draft-ietf-httpbis-header-structure.md
This algorithm automatically enforces the ABNF syntax, including length limits.
It still punts on the actual strtoi/strtof part.
Closes #475 ?
> write a number algorithm that matches ABNF

- draft-ietf-httpbis-bcp56bis.md
This just fixes a typo, but this text has more problems.
I'm having trouble connecting this final sentence to the text that precedes it.  I think that the point is that including a body on GET is unwise because it might cause explosions.  A point about side effects needs far more exposition, especially since GET is defined to be free from overt side effects (safe, idempotent, and all that business).  If this were just another statement and the "As a result" is dropped, that's different.
> Get and side effects fix

- draft-ietf-httpbis-rfc6265bis.md
There is currently a discrepancy in the spec regarding invalid values
in the SameSite cookie attribute.
For example, this cookie:
Set-Cookie: foo=bar; SameSite=bogus
is expected to be dropped entirely according to the "Server Requirements"
under Section 4.1.2.7:
If the "SameSite" attribute's value is neither of these [ "Lax",
"Strict" ], the cookie will be ignored.
whereas under Section 5.3.7 of "User Agent Requirements", the cookie
is to be kept but the attribute is ignored:
If cookie-av's attribute-value is not a case-insensitive match for
"Strict" or "Lax", ignore the "cookie-av".
Additionally, the end of Section 4.1.2 also matches the behavior
described in Section 5.3.7:
User agents ignore unrecognized cookie attributes (but not the entire
cookie).
From a forward-compatibility point …
> Clarify handling of invalid SameSite values (fixes #389)

- draft-ietf-httpbis-rand-access-live.xml
Also considering if "Security Considerations" can be "Compatibility Considerations".
> Added a small blurb referencing client range-end considerations from section 5

- draft-ietf-httpbis-http2-secondary-certs.md
> Abstracts are small

- draft-ietf-httpbis-replay.md
....instead of RFC defining it.
> replay: refer to actual header field registry

- draft-ietf-httpbis-replay.md
According to RFC 7231, Section 8.3.1.
I didn't include anything here about Vary because I wanted to discuss that first and these seemed uncontroversial.  It seems OK to say that Vary is permitted here because we expressly talk about varied reactions based on the presence of Early-Data.  If that's right, I will amend this with a second commit.  (I'm jetlagged, so being a little cautious.)
> Document some of the properties of Early-Data

- draft-ietf-httpbis-replay.md
This was a little obtuse in the previous iteration, likely as a result of trying to be parsimonious.  Expand it a little and clarify the attack.
> Attempt to clarify the replay attack

- draft-ietf-httpbis-replay.md
Our basic list of mitigations missed a fairly obvious one.
Mentioning it should help with the class of confusion Magnus N. had with the draft.
I decided not to include a note about the server being unable to examine early data before making this decision.  That's just something people will need to discover for themselves.  Generally, you have to decide whether you want 0-RTT without seeing any of it.  Partly this is because it avoids a potential deadlock, but mostly it's because the TLS stack will not even decrypt 0-RTT if it is rejected.
> Mention rejection of 0-RTT

- draft-ietf-httpbis-replay.md
use registry URIs consistently
> early-data: iana links

- draft-ietf-httpbis-replay.md
> Treat invalid header fields conservatively

- draft-ietf-httpbis-expect-ct.md
...avoid too wide artwork by changing the second example to use multiple field instances (which, in itself, is good to have in the examples anyway)
> expect-ct: tune examples

- draft-ietf-httpbis-http2-secondary-certs.md
Fixes #632.
They were both special, but for some reason the first reference wasn't getting brackets in the text output.  Putting whitespace between them doesn't affect that, but putting other characters does.
> Encourage kramdown to use brackets

- draft-ietf-httpbis-header-structure.md
Separate parsing out, and add serialisation. Also, allow referencing specs to use ABNF.
> Restructure structure

- draft-ietf-httpbis-http2-secondary-certs.md
Fixes #617.
Specifies an exporter-derived value in SETTINGS to prove that the TLS connection is between the same endpoints as the HTTP connection.  If there is a TLS-terminating proxy intermediating the connection, the expected value will not match the received value, and the work of producing exported authenticators can be skipped.
One open question is around the use of early exporters.  I think this is probably something we want, so that servers can send additional certificates in their 0.5-RTT flight to 0-RTT clients.  However, should clients be required to supply a value derived from a regular exporter after the handshake finishes?  This is a minor pain in H2, but in HTTP/QUIC would require defining a separate frame type to carry the updated token.  The obvious value is that the …
> Man-in-the-middle protection via SETTINGS

- draft-ietf-httpbis-http2-secondary-certs.md
Follow-on to #586; in the process of fixing this, I noticed that I'd added a "server" header but missed adding a corresponding "client" header, so the client discussion appeared in the server section.
> Clients use Empty Authenticator as well

- draft-ietf-httpbis-http2-secondary-certs.md
Capitalized section headers throughout; sentence-cased figure captions.  Both were previously a mix throughout the document.
> Adjust casing in Section Headers and figure captions

- draft-ietf-httpbis-replay.md
@kaduk had a few comments in the review of this that are easy to solve.
> Ben's comments

- draft-ietf-httpbis-client-hints.md
Per discussions in fetch#726 [1], update the opt-in example to apply to
same-origin resources only, with Accept-CH-Lifetime being processed on
navigation requests.
[1] https://github.com/whatwg/fetch/issues/726
/cc @yoavweiss @tarunban
> Accept-CH+Lifetime opt-in is for same-origin resources

- draft-ietf-httpbis-cache-digest.md
Aligns with other SETTINGS parameter names defined in other docs.
> Add SETTINGS_ prefix to parameter names

- draft-ietf-httpbis-header-structure.md
Fix #664. Step 4.4 equates "the range %x00-1f or %x7f" to "not in VCHAR", but VCHAR doesn't include %x20; this change adds "or SP" and imports SP from RFC5234.
> Fix VCHAR references in draft-ietf-httpbis-header-structure.md

- draft-ietf-httpbis-header-structure.md
This corresponds with the ABNF in the #param section.
> Add ";" missing from #ser-param-list

- draft-ietf-httpbis-header-structure.md
Serialisation algorithms for dictionary and parameterised-list didn't include commas (?)
This copies the equivalent steps from the `list` algorithm
> [SH] add commas to dict,plist algorithms

- draft-ietf-httpbis-header-structure.md
When parsing a number, multiply `sign` back in to `output_number`
*before* testing against the range defined in Section 3.5.
> [SH] multiply int by sign before testing range

- draft-ietf-httpbis-header-structure.md
Serialised `value` wasn't getting appended to `output`
> [SH] make Serialising an Item return a value

- draft-ietf-httpbis-header-structure.md
Makes "Parse a Number from Text" not be greedy, and return (not fail) when it encounters a non-digit character.
Resolves #668
> [SH] make 'parse number from text' less greedy

- draft-ietf-httpbis-header-structure.md
Serialisation of dictionary and param-list currently say `identifier=key` instead of `key=item`
This fixes that.
> [SH] fix key=item serialisation

- draft-ietf-httpbis-header-structure.md
the `boolean` ABNF rule is case-*in*sensitive, but the algorithm for parsing (and the test case in the separate repo) enforce capitals only.
> [SH] make boolean ABNF case-sensitive

- draft-ietf-httpbis-variants.md
This change passes 'null' to the content-negotiation algorithm if the
request header is absent. For list headers, the algorithms can always
turn that into the empty list, but for non-list headers they need to
come up with something appropriate to do.
Fixes #731. This also tries to do better about #734, but may not completely fix it.
> Handle absent request headers.

- draft-ietf-httpbis-variants.md
Fixes #570. I think this also fixes #743, but I might have missed something.
Misc changes that aren't actually necessary to use Structured Headers:
* "variant-item" became "variant-axis".
* I defined what clients ("caches"?) MUST do when a server violates one of its MUSTs.
* I removed the (incorrect) `token / "/" / "?" / "\" / "[" / "]" / ":" / "@" / "(" / ")"` definition of available-value in favor of allowing arbitrary [Structured Header strings](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#string). It wasn't clear what excluding characters like `{` was gaining us, and the restriction would have required extra words when parsing the headers.
* I removed {{gen-variant-key}} entirely and had Compute Possible Keys return a list of lists that could be directly …
> Convert Variants to use Structured Headers.

- draft-ietf-httpbis-variants.md
I've also added examples of the new behavior.
This is an attempt to fix #740.
> Requests that match a non-cached variant should go to the origin.

- draft-ietf-httpbis-variants.md
Fixes #747.
@nyaxt @hajimehoshi
> Use versioned header names for draft implementations.

- draft-ietf-httpbis-bcp56bis.md
This change switches from "URL" to "URI" specifically for two contexts:
- URI schemes
- URI syntax
(It might be good to also add an explanation somewhere in the Introduction; I can make a proposal if needed)
> bcp56bis: URI vs URL (see #757)

- draft-ietf-httpbis-bcp56bis.md
- fix one reference
- drop 308 reference, it's now in the base spec
> bcp56bis: redirects

- draft-ietf-httpbis-client-hints.md
As previously discussed, the current state where some CH hints are defined in the IETF draft and some in accompanying specifications is confusing. Furthermore, defining the image related hints in web specifications would be a better fit, as they have direct implications to image processing there.
This PR removes those hints from the IETF draft. This hints are [being added](https://github.com/yoavweiss/html/commit/7bd134ec67472303d06700686be5d37d45ada048) to the HTML specification as part of a larger Client Hints related PR.
> Remove image-related Client Hints

- draft-ietf-httpbis-client-hints.md
Tweak/cleanup in light of #775
> Deleted intro’s promise of an “initial set of Client Hints”

- draft-ietf-httpbis-http2-secondary-certs.md
Fixes #486.  Takes a dependency on https://github.com/tlswg/tls-exported-authenticator/issues/43.
> Request-ID matching

- draft-ietf-httpbis-proxy-status.md
See <https://www.rfc-editor.org/styleguide/part2/>, "Referring to specific sections within another document"
> proxy-status: fix section reference formatting

- draft-ietf-httpbis-header-structure.md
It pains me, but I understand.  This changes the name of one of our types (including the section header), and (internal) section references, but I think it's still editorial.
see #791
> [SH] Americanise spelling of serialise and parameterise

- draft-ietf-httpbis-rfc6265bis.md
Based on the discussion in httpwg/http-extensions#594, this patch aligns
the specification with Firefox's status quo behavior: allowing
`SameSite=*` cookies to be set from all top-level navigations, not just
navigations for which `SameSite=*` cookies would also be sent.
> RFC6265bis: Allow `SameSite` cookies to be set for all top-level navigation

- draft-ietf-httpbis-header-structure.md
Fixes #781.
This modifies parsing to consider empty or not-present header fields as
empty containers; serialisation omits them from output.
> Allow empty dictionaries and lists.

- draft-ietf-httpbis-http2-secondary-certs.md
Fixes #714 and fixes #715, filed by @LPardue.  Given #480, the AUTOMATIC_USE text is entirely superfluous, and given #566, the correct wording would be "for a stream."
> Remove dangling reference

- draft-ietf-httpbis-digest-headers.md
States that `MD5` MUST NOT be used.
Sets the MD5 status to deprecated.
> md5 must not be used

- draft-ietf-httpbis-client-hints.md
Based on discussion at IETF 105, removing explicit lifetime in favor of
implicit opt-in registration and persistence.
@martinthomson can you please take a look? In particular, current language states the preference should be persisted but doesn't explicitly state for what the lifetime is.. Modulo, in privacy section we do talk about MUST criteria for clearing it. Any suggestions or recommendations for how to best approach this?
> Remove Accept-CH-Lifetime

- draft-ietf-httpbis-header-structure.md
Inner list values are space-separated.
> Mixed dictionary typos.

- draft-ietf-httpbis-header-structure.md
Incidentally fixes in #918 by removing the annotation.
According to IEEE's site and references the target should be <https://ieeexplore.ieee.org/servlet/opac?punumber=8766227> but I've kept the equivalent of the current address.
> [SH] reference IEEE 754-2019

- draft-ietf-httpbis-digest-headers.md
Simplifies references to sha algorithms pointing to RFC 6234
instead of FIPS180 documents.
> Fix: #832. Reference RFC6234 instead of FIPS180.

- draft-ietf-httpbis-digest-headers.md
Obsolete ADLER-32 but don't forbid it. #828
> Obsolete ADLER-32 but don't forbid it. It's now NOT RECOMMENDED #828 

- draft-ietf-httpbis-digest-headers.md
to use the new "validator" name. See: 
- https://tools.ietf.org/html/rfc7231#section-7.2
- https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#response.validator
> Replace cache-validator with validator (rfc 7231 section 7.2)

- draft-ietf-httpbis-digest-headers.md
Replaces the old `cache-validator` with `validator` from https://tools.ietf.org/html/rfc7231#section-7.2
The relations of Last-Modified and ETag with Digest are examined in #937
> Refresh validator definition. #936

- draft-ietf-httpbis-proxy-status.md
Rationale for 503 is that the service is unavailable due to too many
connections.
429 could potentially be an option as well, but that seems more specific to a single user hitting a rate limit, while `connnection_limit_reached` seems more related to a global limit.
/cc @mnot @PiotrSikora
> Specify recommended HTTP status code for connnection_limit_reached

- .circleci/config.yml
I think that narrowing this to `.git` should suffice.  A copy of the i-d-template and Julian's XSLT repositories are cached in the docker image.
> Stop over-caching

- .circleci/config.yml
The caching of `.git` leads to interesting issues on circle, which has a bug in its checkout logic for tags.  This works around that by pulling instead.  That's complicated by the fact that circle insists on using SSH for pulls.  That is great for ensuring that they can pull private repos, but this workaround - which runs before the circle key is available - can't use that and the origin is configured poorly.
> Fix caching for tags by fetching them first

- draft-ietf-httpbis-digest-headers.md
Clarifies the "returned value" expression.
Fixes: #967
> Fix: #967. Clarify the _returned value_ expression.

- draft-ietf-httpbis-digest-headers.md
clarify editorial rendering of binary payloads
> Fix: #980. Clarify binary payload is b64 encoded

- draft-ietf-httpbis-header-structure.md
For #992.
Note that this makes missing values `True`; if we like that approach, I think we should do it for missing parameter values too (currently they use `null`, which isn't part of our type system).
I used `True` because it aligns with the semantics of current uses nicely.
> Make dictionary values optional.

- draft-ietf-httpbis-header-structure.md
An alternative to #983 - removes HTAB everywhere, replaces `OWS` with `*SP`.
Resolves #998
> [SH] replace OWS with *SP

- draft-ietf-httpbis-header-structure.md
Explicitly disallow thirteen digits before the dot.
> make #parse-number algorithm fail on bad decimals

- draft-ietf-httpbis-rfc6265bis.md
This patch replaces `example.com` with `site.example`, and corrects
inadvertant usage of non-example domains in the hopes of avoiding
confusion.
Closes httpwg/http-extensions#706.
> [RFC6265bis, EDITORIAL]: Use `.example` TLD for examples.

- draft-ietf-httpbis-rfc6265bis.md
This patch alters the cookie parsing algorithm to treat
`Set-Cookie: token` as creating a cookie with an empty name and a value
of "token". It also rejects cookies with neither names nor values (e.g.
`Set-Cookie:` and `Set-Cookie: =`.
Tests in web-platform-tests/wpt#21093.
Closes httpwg/http-extensions#159.
> [RFC6265bis] Accept nameless cookies.

- draft-ietf-httpbis-digest-headers.md
Adds an example of error response. Digest is computed
on the enclosed representation of the error.
imho this example is inferred from the current normative part, clarifies the expected behavior and does not require a change in the normative part.
> Fix: #973. Error response is unrelated to the effective request URI

- draft-ietf-httpbis-rfc6265bis.md
https://github.com/httpwg/http-extensions/pull/1017 was incomplete,
leaving a number of inadvertant references to `*.com` sites, or the
`com` TLD. This patch, hopefully, is less incomplete.
h/t @triple-underscore and @bagder for pointing this out.
> [RFC6265bis, Editorial]: Actually use `example` TLD.

- draft-ietf-httpbis-header-structure.md
Allow "." in `key`. Also consistently reorders character lists for key.
> [SH] allow "." in key

- draft-ietf-httpbis-rfc6265bis.md
> [RFC6265bis, Editorial]: Define "public suffix" in the terminology section.

- draft-ietf-httpbis-rfc6265bis.md
Closes #1032.
@johnwilander @bagder, mind taking a look? John, in particular, you noted "But we should also have an explicit reference in my opinion.", which I didn't really understand. Do you want more than this patch?
> [RFC6265bis, Editorial] Consistently use 'last-access-time'.

- draft-ietf-httpbis-header-structure.md
Small editorial fix.
I'm also not comfortable with "a integer", maybe remove "a"? Anyway that's a nitpick.
> Fix "is can be" (header structure)

- draft-ietf-httpbis-rfc6265bis.md
> [RFC6265bis, Editorial] Typo'd a section number.

- draft-ietf-httpbis-header-structure.md
The term COMMA is not defined anywhere in this document, or in any of the documents it imports. But we can just use the literal `","` instead.
Fixes: #1053
> Replace COMMA with ","

- draft-ietf-httpbis-priority.md
Based on our side meeting during QUIC interim, this PR makes following changes:
* Reduce semantics associated to urgency levels. Clients can now use the 8 levels in the way they like, with the only restrictions being: default=3, background=7.
* Stop using upper-case keywords for how the responses should be prioritized, or how server-provided parameters should be incorporated.
> Minimize the semantics of urgency

- draft-ietf-httpbis-header-structure.md
Round to three decimal places first, then check the domain, then do all the actual serialising.
It's potentially not very l13n-friendly; feel free to change "decimal point" or "to the left" etc., if something is more appropriate.
Fixes #1043
> make serialise decimal algo round early, fail fast

- draft-ietf-httpbis-client-hints.md
When merging the different PRs, the "Cost of adding hints" section was misplaced and it wound up in the middle of the security section. This fixes that (and bumps the revision number).
> Fix merge issues with "cost of adding hints" section

- draft-ietf-httpbis-rfc6265bis.md
This could allow us to register 'priority' in a separate document
without angering the Powers That Be.
@mnot: Does this more or less match what you were expecting?
> [RFC6265bis] Add a cookie attribute registry.

- draft-ietf-httpbis-priority.md
We still had usage of the term override, so while thinking how to address that I took the opportunity to state explicitly that no guidance is provided for how an intermediary might merge.
> priorities: remove last vestiges of override

- draft-ietf-httpbis-header-structure.md
* Change "removing the first character" to "consuming the first character" in `#parse-key`
* Add "as" for consistency in `#ser-item`
* Correct `parameter-name` to `param_name` in `#ser-params`
> Minor structured header nits

- draft-ietf-httpbis-priority.md
We landed a change to remove the semantic meanings
of urgency levels but neglected to remove a considerations
section that discussed this.
This PR moves some of the still relevant text out of the section
and nukes the stuff no longer needed.
> editorial tidyup around urgency meanings

- draft-ietf-httpbis-header-structure.md
This change to the key syntax allows dictionaries and parameters to use "*" as a starting character for names, allowing keys like
*
*value*
*my*god*its*full*of*stars*
Closes: #1068
> Allow "*" for sh-dict member and parameter names

- draft-ietf-httpbis-digest-headers.md
@ioggstream I was tired of the warnings of line too long, so I've reflowed a lot of the examples and also most of the text while I was at it. The Python code example was tricky, please pay attention to that as I may have mangled it.
> digest: reflow text and examples to quell warnings

- draft-ietf-httpbis-header-structure.md
Changes:
behaviour -> behavior (and related words)
parameterised -> parameterized
serialise -> serialize (and related words)
unrecognised -> unrecognized
Closes: #1085
> Standardi{sz}e on US English spelling

- draft-ietf-httpbis-priority.md
A few editorial tweaks to improve readability, including some x-refs to the Header / frames.
The most contentious change is at L262, the sentence read a bit weird so I juggled it around to make the intent (as I understand it) clearer.
> fix some editorial hangovers

- draft-ietf-httpbis-digest-headers.md
Postpone the representation-data in Annex B.
This is because this section explains the http semantics but does not contain normative information.
NB: I retained the initial statement, which we will refactor lately.
> Put representation-data examples in Annex B. See #1103.

- draft-ietf-httpbis-digest-headers.md
Reorder Digest section. Cumulative PR of:
- #1122 
- #1123 
@LPardue this patch ends the reordering [preview](https://httpwg.org/http-extensions/ioggstream-1103-cleanup-digest/draft-ietf-httpbis-digest-headers.html) 
and achieves:
- Digest header defined at §3 (pag. 7)
- Non-normative section moved in Annex
Fixes #1103. Replaces #1091
> Fixes: #1103. Complete editorial reordering of Digest

- draft-ietf-httpbis-digest-headers.md
Fixes formatting issue in digest-algorithms [preview](https://httpwg.org/http-extensions/ioggstream-editorial-2/draft-ietf-httpbis-digest-headers.html)
using vspace from here https://github.com/cabo/kramdown-rfc2629#experimental-features
eg.
```
{: vspace="0"}
term
:  * bullet
* list
```
```
> Avoid errors on EOL trimming.

- draft-ietf-httpbis-header-structure.md
Some of this is rewording.
There are two new paragraphs talking about extensions: one deals with dictionaries, the other deals
with extensions to a SH definition.
I also removed the "starts with 'h'" example for greasing.  We know that X- lead to all sorts of
mess, so choosing a bad example here could be just as bad.  I'm happy to split that out or be talked
into backing it out, of course.
> Some suggestions for forward compatibility

- draft-ietf-httpbis-digest-headers.md
The PR is intended to fix #1137, which asks us to use updated terminology in HTTP core documents.
I've attempted to update all references of RFC 7230 to draft-ietf-httpbis-semantics. A reference to RFC7231 remains but is demoted to informative.
The change converts `Digest` and `Want-Digest` into `fields` meaning they can appear in header or trailer field sections. As noted there is a clear case for Digest trailers, there seems no reason to restrict Want-Digest to request header fields but I can be easily persuaded.
Remaining references to `header fields` relate to externally defined headers that are coined in draft-ietf-httpbis-semantics.
Finally, the IANA registry handling is also updated.
> Reference new HTTP core semenatics and use field terminology

- draft-ietf-httpbis-rfc6265bis.md
Nameless cookies serialize as `value`. Valueless cookies serialize as
`name=`. No, this isn't what we would have chosen if we were designing
cookies from scratch, but it's Chromium and Firefox's shipping behavior,
and it's reasonable to just accept.
This specification change is covered by 0021 and 0022 in the WPT
repository (see
https://wpt.fyi/results/cookies/http-state/general-tests.html?label=master&label=experimental&aligned).
Closes https://github.com/httpwg/http-extensions/issues/1081.
> [RFC2665bis] Fix nameless/valueless serialization.

- draft-ietf-httpbis-rfc6265bis.md
The 'secure-only-flag' is never "not set". It is either "true" or
"false". This patch fixes two places where we should have been checking
for falsity.
Closes https://github.com/httpwg/http-extensions/issues/1059.
> [RFC6265bis] Fix 'secure-only-flag' processing.

- draft-ietf-httpbis-rfc6265bis.md
This patch incorporates two ABNF changes:
1.  Closes https://github.com/httpwg/http-extensions/issues/1074 by
adjusting the `cookie-pair` grammar to include optional spaces.
We test this behavior in a few distinct WPTs, including
chromium0014, name0018, value0006.
2.  Closes https://github.com/httpwg/http-extensions/issues/1119
by removing OWS from the spec, as user agents generally follow
the "SHOULD" in the current text to limit themselves to a single
SP rather than serializing with OWS. It's reasonable to lock that
in, and it also happens to match all the `Cookie:` header tests
we have.
Thanks to both @reschke and @bakulf for paying attention to this.
> [RFC6265bis] Fix ABNF.

- draft-ietf-httpbis-http2-secondary-certs.md
Fixes #869.  The intent here is to say that your requirements for trusting a secondary certificate should be at least as strict as for trusting additional names in the primary certificate.
> SHOULD check DNS for secondary if you would have for primary

- draft-ietf-httpbis-header-structure.md
Editorial: add one reference to Structured Trailers in a list of the types, and
correct what appears to be a typo of Structured Field --> Structured Trailer.
> Add references to Structured Trailers

- draft-ietf-httpbis-digest-headers.md
"validator" refers to validator fields used in preconditions. The term validator fields seems more faithful to the original cache-validators in RFC3230.
https://github.com/httpwg/http-core/blob/master/draft-ietf-httpbis-semantics-latest.xml#L9288
and
https://tools.ietf.org/html/draft-ietf-httpbis-semantics-07#section-10.2
> Replace validator -> validator fields

- draft-ietf-httpbis-digest-headers.md
- draft-ietf-httpbis-rfc6265bis.md
Mention trailers.
```
If received in trailers, Digest MUST NOT be discarded; instead it MAY be merged in the header section (See Section 7.1.2 of {{!MESSAGING=I-D.ietf-httpbis-messaging}}).
```
See #884
> Start mentioning trailers. See #884.

- draft-ietf-httpbis-http2-secondary-certs.md
Fixes #1087.  Instead of a four-byte exporter, uses an eight-byte exporter and splits into two values.  Support for exchanging server certificates and client certificates is now indicated separately.
> Split setting into client and server values

- draft-ietf-httpbis-http2-secondary-certs.md
Fixes #1088, though I'm not sure it's yet precise enough.  There are three general classes of errors:
- The peer **did something wrong**.  There are relatively few of these possible -- indicating more certificates to use than were requested, or more than one unsolicited certificate; sending CERTIFICATE_NEEDED to a peer that didn't indicate support for this extension.
- The **authenticator is corrupt**.  This might indicate a problem with the TLS connection.
- The **certificate isn't acceptable**.  There are lots of reasons this might happen.
The first two should be at least stream and possibly connection errors.  The latter should be handled at the HTTP layer, but previously had error codes defined for them.  This PR removes several error codes and recommends handling at the HTTP layer if …
> Secondary Cert error handling

- draft-ietf-httpbis-http2-secondary-certs.md
Automatic use of client-proffered certificates was removed a while back; clients can indicate which certificate (if any) they want the server to consider by sending a `USE_CERTIFICATE` frame with the `UNSOLICITED` flag set.
There was text talking about automatic use of the server-proffered certificates, but there wasn't corresponding text disallowing that behavior for client certificates, simply the absence of permission.  This PR forbids considering "available" certificates until the client indicates which certificate to use.
Fixes #1090.
> Confused deputy should be clear

- draft-ietf-httpbis-priority.md
When we discussed removing the semantics of urgency levels, we also
thought it would be a good idea to change the default from 1 to 3.
We agreed to do this and landed a change that removed the semantic
text but unfortunately forgot to also change the default.
This change simple fixes the oversight.
> Default urgency is 3

- draft-ietf-httpbis-header-structure.md
> Allow Lists and Dictionaries to be delimited by OWS

- draft-ietf-httpbis-digest-headers.md
(inserted with https://github.com/httpwg/http-extensions/commit/4178324c374fd1e75acda09df6d7b2afb232de07)
> digest-headers: remove non-ASCII characters from prose

- draft-ietf-httpbis-message-signatures.md
Version -00 was published to the data tracker from an XML file. This is the first conversion to Markdown and commit to the WG repo. No changes to semantics, only minor formatting changes due to the conversion.
> Initial commit of message-signatures-00 draft, converted to Markdown.

- draft-ietf-httpbis-priority.md
Since fairness is being moved out of security considerations, (https://github.com/httpwg/http-extensions/pull/1224) it makes the section empty.
Seems reasonable to add some prose about the considerations of this scheme as compared to HTTP/2. However, this also depends on the outcome of the reprioritization discussion, so I'm being a little weasly with TBD and TODOs.
Might want to just hold onto this for a while but WDYT @kazuho ?
> Rough in priorities security concerns

- draft-ietf-httpbis-rfc6265bis.md
Add what seems to be a missing word in the __Host example text.
> Fix __Host prefix example wording

- draft-ietf-httpbis-rfc6265bis.md
Fixes [#1234](https://github.com/httpwg/http-extensions/issues/1234).
> Move empty cookie-name and empty cookie-value check from 5.3 to 5.4

- draft-ietf-httpbis-digest-headers.md
- HTTP 1.1 messaging is not normative
- replaced "message body" with a periphrases
> Fix: #1215. HTTP/1.1 messaging is not normative anymore.

- draft-ietf-httpbis-digest-headers.md
- explicits that digest does not depend from multiple transfer coding
> Fix: #884. multiple transfer coding

- draft-ietf-httpbis-digest-headers.md
clarifies that no normative parts were added to Want-Digest, only examples.
> Fix: #968. Clarifications on Want-Digest.

- draft-ietf-httpbis-digest-headers.md
Clarifies the following points:
- resource identification is inherited from SEMANTICS
- validator fields (ETags & Last Modified) which apply to the identified resource, apply to Digest too.
> Fix: #936. Cache semantics impacts on Digest and on the representation.

- draft-ietf-httpbis-digest-headers.md
Removes reference to validators as their use is now inferred from http spec.
> Remove references to "validator fields"

- draft-ietf-httpbis-digest-headers.md
Adds more consistent editorial rules:
- headers are always backticked to ease readability
- qvalue is quoted like in SEMANTICS
- new digest-algorithms are quoted like content codings in SEMANTICS
> Digest: editorial work (quoting, casing, ..)

- draft-ietf-httpbis-digest-headers.md
Aligns a part of the doc with the SHA-1 deprecation we decided in #1020 
We correctly deprecated SHA-1 but in this part we left it as NOT RECOMMENDED.
> We forgot to align this part with the SHA-1 deprecation.

- draft-ietf-httpbis-digest-headers.md
- is preliminary to #1253 
Consistently use `digest-algorithm` instead of `digest algorithm`.  In case we need to further focus on the value, we can say `digest-algorithm value` or `digest-algorithm token`.
Looking at "content-coding" vs "content coding" in https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html I think that this choice makes the document more readable.
> Always use digest-algorithm (with dash). See #1211.

- draft-ietf-httpbis-digest-headers.md
- use lowercase for digest-algoritms in the doc
- case is unchanged when referring to the actual algorithms (eg. SHA-1)
- prefer lowercase for digest-algorithms
- update IANA table to use lowercase digest-algorithms
digest-algorithms remain case insensitive
Fixes #1211 Discussion here https://lists.w3.org/Archives/Public/ietf-http-wg/2020JulSep/0119.html
> Fix: #1211. Prefer lowercase digest-algorithm names.

- draft-ietf-httpbis-priority.md
This attempts to address #1096 and #1079. It might help towards overcoming the headers vs frames debate.
I made the call to restrict the PRIORITY_UPDATE frame to only be sent by clients.
It replaces ASCII art with new QUIC-style frame definitions.
> PRIORITY_UPDATE can be used for initial priority, split H3 frames into two types

- draft-ietf-httpbis-priority.md
The old text had a loose definition of when to apply buffered frames.
It also had a fair amount of repetition.
This change tweaks the sections a bit so that we have one that discusses
how a server should handle PRIORITY_UPDATES for either initial signal or
reprioritization. It incorporates the suggestions on issue #1260 mixed
in with some text we already had.
There is still a question about how an implementation can limit its buffering commitments, which depends on the servers applications ability to access stream information. This might no be exposed by a QUIC library for instance. I suggest we punt on that unless there is something easy we can capture now.
Closes #1260
> Better explain PRIORITY_UPDATE buffering and application

- draft-ietf-httpbis-priority.md
As noted in the discussion on #1267, there is some asymmetry between the Priority header and PRIORITY_UPDATE frame. This PR addresses the dichotomy by localized description of the frame. I've avoided great exposition of the dichotomy because I feel it could be wordy and distracting; others might disagree.
The changes dovetail nicely with the discussion #1268 about how to handle parsing failures. So adding that at the same time.
Closes #1267 and #1268 
cc: @martinthomson @dtikhonov @kazuho
> Describe frame/header dichotomy and error handling for SFV failures

- draft-ietf-httpbis-priority.md
> Be less specific about urgency when behind an intermediary

- draft-ietf-httpbis-priority.md
This tries to address two sets of comments on "what signals are subsumed by priority hints" and "how should a server implement things". 
One aspect of this is setting client expectations straight; they should have a vague idea what will happen if a server plays ball but also expect that servers can and will do whatever they want.
The other aspect of this is describing what signals servers have at their disposal, and presenting some of the gotchas or tradeoffs that might happen if the extensible priority scheme is implemented too matter-of-fact. Some people would like to see more explicit guidance for servers, that's a fine request. However, I don't see how any single scheduling algorithm would work for the range of vendors and deployments that have shown an interest Priorities, so I've …
> rough in server scheduling guidance

- draft-ietf-httpbis-priority.md
Fixes #1277 
@dtikhonov correctly pointed out that the draft contained a made up error code. On inspection, we need to define specific error codes for both H2 and H3. This change does that.
> fix the error type when PRIORITY_UPDATE is bogus

- draft-ietf-httpbis-message-signatures.md
- Strengthened requirement for content identifiers for header fields to be lower-case (changed from SHOULD to MUST).
- Relaxed guidance on processing Creation Time and Expiration Time to only require verifiers to examine them and test against the verifier’s requirements.
- Minor editorial corrections and readability improvements.
Resolves #1187, resolves #1188
> Incorporating WG feedback

- draft-ietf-httpbis-digest-headers.md
details encryption quirks:
- encryption functions may produce different results with the same data
- this means that if I GET an encrypted resource twice, I could get two different digest values
- so the digest value is just good to validate the ongoing message and not for further processing of the data at rest, unless I store the encrypted data or use an `id-` algorithm which in turn might disclose information.
This
> Detail encryption quirks

- draft-ietf-httpbis-message-signatures.md
Change to specification text was reverted.
> Removed reverted Expiration Time change from changelog.

- draft-ietf-httpbis-digest-headers.md
sha is deprecated, not obsoleted.
> Typo: sha is deprecated, not obsoleted.

- draft-ietf-httpbis-message-signatures.md
* Replaced unstructured `Signature` header with `Signature-Input` and `Signature` Dictionary Structured Header Fields.
* Defined content identifiers for individual Dictionary members, e.g., `x-dictionary-field:member-name`.
* Defined content identifiers for first N members of a List, e.g., `x-list-field:4`.
A signature in a request now looks like this:
```http
Signature-Input: sig1=(*request-target, *created, host, date,
cache-control, x-empty-header, x-example); keyId="test-key-a";
alg=hs2019; created=1402170695; expires=1402170995
Signature: sig1=:K2qGT5srn2OGbOIDzQ6kYT+ruaycnDAAUpKv+ePFfD0RAxn/1BUe
Zx/Kdrq32DrfakQ6bPsvB9aqZqognNT6be4olHROIkeV879RrsrObury8L9SCEibe
oHyqU/yCjphSmEdd7WD+zrchK57quskKwRefy2iEC5S2uAH0EPyOZKWlvbKmKu5q4 …
```
> Adopting Structured Fields

- draft-ietf-httpbis-client-hints.md
- sf.json
(FYI, if you're too far into AUTH48 don't worry about merging this, although the RFC Editor might want those sections annotated, and if so, the whitespace should be removed from the beginning of the lines)
> Validate http headers in CH

- draft-ietf-httpbis-message-signatures.md
- sf.json
This annotates examples with `http-message` so they can be validated; I corrected the errors I saw.
One outstanding issue is that you're wrapping long binary content across multiple lines, and HTTP line folding rules means that doing so inserts whitespace, which isn't allowed in structured binary content.
Two possible solutions:
1. Make a note near the top that it's wrapping these long lines for illustrative purposes only, and that they're not valid; I can adjust the tooling to make it validate properly despite that
2. Change structured binary content's definition to allow whitespace
(2) is unlikely, because that document is in the RFC Editor queue, but not impossible.
> Validate Structured Fields, with adjustments

- draft-ietf-httpbis-rfc6265bis.md
Opening for discussion, per the last interim group meeting.
This should correspond to https://tools.ietf.org/html/draft-west-cookie-incrementalism-01#section-3.1
> Treat cookies as "SameSite=Lax" by default.

- draft-ietf-httpbis-rfc6265bis.md
This clarifies the question raised in issue #773 about SameSite cookies on redirects.
> RFC 6265bis: SameSite -- clarify request method on redirects

- draft-ietf-httpbis-digest-headers.md
Provides non normative feedback on mangling field value might invalidate signatures.
> Fix: 851. Mangling might invalidate signatures.

- draft-ietf-httpbis-rfc6265bis.md
Opening for discussion, per the last interim group meeting.
This should correspond to https://tools.ietf.org/html/draft-west-cookie-incrementalism-01#section-3.3
> Introduce "Schemeful Same-Site" cookies.

- draft-ietf-httpbis-rfc6265bis.md
It looks like this was forgotten in #1325, when unknown values were switched from None to Default.
/cc @mikewest this caused us some confusion over in Go, if you have time I'd appreciate hearing what you think we should do in golang/go#36990. Thank you!
> Remove leftover paragraph about unknown SameSite values

- draft-ietf-httpbis-digest-headers.md
- fixes examples where Digest was not computed on the actual bytes in the examples
- warns about Digest computation in the examples.
@bc-pi could you please have a look and check if this works for you?
@LPardue where can we provide editorial conventions used in the examples?
> Fix: #1349. Include spaces in digest computation.

- draft-ietf-httpbis-priority.md
Fixes #1261.
When the ID discusses PRIORITY_UPDATE frame element ID for HTTP/2,
@MikeBishop rightly pointed out that HTTP/2 doesn't have HTTP/3's 
notion of stream limits. So this text tries to reframe things in
terms of the concurrency window.
I might have gone too far here. Given the guidance we give about
buffering PRIORITY_UPDATE, and the fuziness of concurrency window and
upper limts to idle but openable streams, I don't think its right
to recommend that servers treat it as a conenction error. 
Interested to see what others think of the PR/
> priority: HTTP/2 doesn't have stream limits

- draft-ietf-httpbis-priority.md
Fixes #1056.
There's been a fair amount of discussion on how a server should 
treat server push prioritization. This PR attempts to be highlight
some of the consideration a server should make and highlight that
there is no general advice, and ergo no safe default.﻿
> Describe considerations for server push prioritisation

- draft-ietf-httpbis-digest-headers.md
- references RFC6515 and 6194 for deprecating md5 and sha1
Since there are RFCs, we could even skip explaining that those algorithms are vulnerable to collisions.
> Fix: #1392. Reference RFC 6515 and 6194 for deprecating md5 and sha1.

- draft-ietf-httpbis-message-signatures.md
This removes the in-document "issues" list and background introduction note paragraph, in line with the document's status as a working group draft backed with an issue tracker.
All removed items should have corresponding issues tagged with `signatures` in this repository's issue tracker (some have already been closed), so keeping them in the document was redundant and artificially inflated the page count.
> clean up editorial notes and issues list

- draft-ietf-httpbis-rfc6265bis.md
Addressing the questions raised in issue #628
> RFC 6265bis: Clarify same-site for reload navigations

- draft-ietf-httpbis-message-signatures.md
removes algorithm specific rules for content identifiers
Current layout is not backward compatible with http-signatures, so it's safe to do it.
> Fix: #1190. Remove algorithm specific rules for content identifiers.

- Makefile
> Install SF validator only when not present

- draft-ietf-httpbis-rfc6265bis.md
It looks like Steven got rid of "scheme/host/port triple" in #1348, so this just covers using "opaque origin".
PTAL @chlily1 @englehardt 
(changelog commit will get pushed as soon as I have a PR URI)
> Fixes #1337 - Align on HTML terminology for origins

- draft-ietf-httpbis-message-signatures.md
Update the signature input method to always require the signature parameters to be covered.
Redefine all fields like `@request-target` as specialty input fields (non-headers) and allow extension by registry.
﻿Define signature parameters using structured field semantics.
Define canonicalization rules more directly.
> Update signature input methods and requirements

- draft-ietf-httpbis-rfc6265bis.md
This adds explicit steps to handle control characters in set-cookie-strings.
> RFC 6265bis: Specify handling of CTL characters in set-cookie-string

- draft-ietf-httpbis-message-signatures.md
Update signature method definitions.
Updated algorithm and key selection process for both sign and verify.
Removed `hs2019` definition.
Examples are not yet updated against new algorithm and key selection guidelines (should target a future PR for this?)
> Update Signature Method Definitions

- draft-ietf-httpbis-digest-headers.md
Clarifies `Server Returns No Representation Data`.
1- `Digest` + HEAD is used to get a resource checksum
2- no Digest in request for clarity
3- only use sha-256 to focus on the actual example.
Fix: #1357
> Fix: #1357. Clarify Digest+HEAD.

- draft-ietf-httpbis-digest-headers.md
- clarifies that you can always ignore `Digest`
- you can ignore `Digest` when using SRI
- if you validate both, it is nice to provide useful errors
> Fix: #1363. Non-normative options in conjuction with SRI.

- draft-ietf-httpbis-digest-headers.md
> Mark's suggestions in section 3 and 4

- draft-ietf-httpbis-digest-headers.md
> Mark's review on section 5. See #1250

- draft-ietf-httpbis-rfc6265bis.md
This adjusts the ABNF for Set-Cookie and Cookie to define field values, not the whole field line, addressing #1302.
> RFC 6265bis: Update ABNF to define field values

- .gitignore
- README.md
- draft-ietf-httpbis-client-cert-field.md
- draft-ietf-httpbis-client-cert-header.md
This is an initial translation of the newly adopted draft.  Output comparison [here](https://tools.ietf.org/rfcdiff?url1=https://www.ietf.org/archive/id/draft-bdc-something-something-certificate-05.txt&url2=https://MikeBishop.github.io/http-extensions/certificate_draft/draft-ietf-httpbis-client-cert-header.txt).
> Certificate draft

- draft-ietf-httpbis-rfc6265bis.md
This PR refactors the cookie retrieval algorithm that formerly lived in `The Cookie Header` section to a new `Retrieval Model` section that mirrors the more generic `Storage Model` section for cookie setting.
This didn't require too much legwork in the end. Of note, I've moved us over from working with a [request-target](https://tools.ietf.org/html/rfc7230#section-5.3) to [target URI](https://tools.ietf.org/html/rfc7230#section-5.1). A request target may not be a full URI (i.e., the "origin form" is a path + query), but we want a full URI so we can call the retrieval algorithm with a Document's URI for non-HTTP APIs. This was mostly a drop-in replacement in the rest of the doc, but I did remove one section that elaborated on extracting a path from the different forms of a request target. …
> [6265bis] Refactor cookie retrieval algorithm to support non-HTTP APIs

- draft-ietf-httpbis-rfc6265bis.md
> RFC 6265bis: Add Lax-allowing-unsafe SameSite enforcement mode

- draft-ietf-httpbis-digest-headers.md
This change is done while ignoring the fact that we might want a bigger document reshuffle when bringing in a "content-digest" header. But it helps illustrate how the abstract / intro could be editorialized to address some off-list feedback.
> digest: editorial over abstract and intro

- draft-ietf-httpbis-digest-headers.md
> Mark's review on section 3.

- draft-ietf-httpbis-digest-headers.md
- moved normative parts in `Digest`
- warn that trailers can be dropped by intermediaries.
> Fix: #1487. Trailers considerations.

- draft-ietf-httpbis-rfc6265bis.md
The IANA Cookie Attribute Registry does not exist yet. It is requested that IANA create it. Clarify wording to reflect this.
Addresses #1426
> 6265bis: Clarify IANA registry wording

- draft-ietf-httpbis-rfc6265bis.md
This change introduces the notion of a user agent's cookie policy, briefly explains it, and refers to it in how cookies may be ignored and in user controls. Before this change, a few sections indicated that the user agent MUST accept set-cookie headers while later relaxing that with a reference to privacy/security settings and user controls.
> Clarified the ways cookies may be ignored.

- draft-ietf-httpbis-message-signatures.md
This text should be more precise about the definition of different signature parameters, including inputs to PSS.
All examples have been updated.
Examples for ECDSA and HMAC have been added.
> Update signature algorithm definitions

- draft-ietf-httpbis-message-signatures.md
Remove the list prefix parameter operation on structured headers. This was previously added to allow for signing of a subset of combined headers, but since the combined header value cannot be considered a structured header value, the prefix functionality did not ultimately serve this purpose.
However, common cases such as adding additional `Via` headers to a request could still be covered by a different mechanism.
Note that dictionary key indexing is still allowed and facilitates multi-signature use cases.
﻿
> Remove List Prefixes

- draft-ietf-httpbis-client-cert-field.md
I've opened issues for the things that were previously TODO comments in the draft; this removes them from the draft itself.
> Remove TODOs

- draft-ietf-httpbis-priority.md
Define deprecation of H2 priority as action, rather than defining it as a concept of "deprecation" then using that term to define the action.
Probably resolves the first half of #1500.
> define H2 priority deprecation directly as action

- draft-ietf-httpbis-priority.md
Let's use friendlier names for the HTTP and QUIC documents
> switch ref links and style

- draft-ietf-httpbis-rfc6265bis.md
@chlily1 do you think we should move these requirements into the Set-Cookie parsing algorithm and make them `MUST NOT` instead of `SHOULD NOT`? Or fine to leave as-is?
> Issue #1340 - Update cookie size requirements

- draft-ietf-httpbis-message-signatures.md
This adds several new specialty identifiers for requests and responses to cover the method, authority, scheme, origin, path, query, and status code values of the HTTP message.
It also edits the `request-target` identifier's associated value to remove the verb and the string construction rules and instead align with HTTP Semantics.
> added new specialty content fields, fix request-target

- draft-ietf-httpbis-message-signatures.md
This creates a mechanism to cryptographically bind a response to its associated request by letting the responder sign the signature value of the request, and the requester validate the signature based on their original request's signature.﻿
> Add request/response binding

- draft-ietf-httpbis-message-signatures.md
This adds the `http-message` type to a few more places, and puts the notice banner on the examples that need it (as per the RFC).
Once merged, this should make `http-lint` pass (see #1586)
> Mnot wrapping

- Makefile
No sense in having a linter if you don't lint.
That said, the signatures draft is currently failing validation.  I think that it isn't picking up
the line folding annotations properly.
> Enable linting by default

- draft-ietf-httpbis-rfc6265bis.md
This excludes HTAB (%x09) from the CTL characters that normally cause cookie rejection. HTAB is considered whitespace and is handled separately at a later step in the algorithm. Related to #1531
> RFC 6265bis: Exclude HTAB from CTLs that cause cookie rejection

- draft-ietf-httpbis-rfc7838bis.md
@martinthomson, since you're the other editor here, can you take a look?
Resulting file is at https://mikebishop.github.io/http-extensions/altsvc_adopt/draft-ietf-httpbis-rfc7838bis.txt, but RFCdiff doesn't seem to like the URL.
> AltSvc-bis:  Largely unchanged -00

- draft-ietf-httpbis-rfc6265bis.md
Minor update to the RFC6265bis changelog to mention the change in treatment of the horizontal tab character (now it's essentially handled the same way as space instead of how control characters are handled).
If you think the summary text here should be improved please let me know. Thanks!
> Update RFC6265bis changelog to mention HTAB change

- draft-ietf-httpbis-digest-headers.md
- Add examples for Content-Digest
- add IANA for Content-Digest
- use "Digest fields" instead of `Digest` and `Content-Digest`
- contentMD5 negotiation replaced by Want-Content-Digest
- fix typos (eg. Location header in a request)
> Add examples with Content-Digest

- draft-ietf-httpbis-rfc7838bis.md
Fixes #1634, fixes #1630.
References to all internal sections are now anchors; references to HTTP/1.1, HTTP/2, Semantics, and Caching are updated to the current versions of those documents.
> Update references in Alt-Svc

- draft-ietf-httpbis-safe-method-w-body.xml
so that issues are linked from https://httpwg.org/http-extensions/
> Add github-issue-label PI

- draft-ietf-httpbis-rfc7838bis.md
The changes here are relatively small, but please ensure I didn't miss anything.  Because not all HTTP/3 streams are framed, I restated "on any other stream" to specify "request and push streams," language which I believe remains appropriate for HTTP/2.
In order to keep the frames as identical as possible, I haven't restructured the H3 version with varints, but that's certainly an option.  It would require defining the frame payloads separately, but that's possible.
> Add HTTP/3 support

- draft-ietf-httpbis-digest-headers.md
> Fix: #1542. Add Content-Digest.

- draft-ietf-httpbis-digest-headers.md
- add registration policy cc: @seanturner and @mnot
- according to https://www.rfc-editor.org/rfc/rfc8126.html#section-4.7
Using RFC policy avoids the issues we had to face to refresh the current table.
See #1533
> Fix: #1533. Add registration policy for digest algorithms.

- draft-ietf-httpbis-rfc6265bis.md
The "Weak Integrity" section correctly notes that non-secure cookies can be set by
network attackers, and will be sent to secure origins. This commit notes that the
`__Secure-` prefix is a mitigation against that attack.
> RFC6265bis: [Editorial] Note `__Secure-` as mitigation.

- draft-ietf-httpbis-targeted-cache-control.md
This strengthens the language around Structured Fields so that it's clear they're preferred, and targeted fields are now primarily defined as structured fields.
It still leaves using a Cache-Control parser as an option. If we want to go further, we could remove the paragraph starting with 'However,...' and the two bullet points below that.
Fixes #1606.
> Structured Fields first

- draft-ietf-httpbis-rfc6265bis.md
The general storage model should be consistent with the Set-Cookie header parsing model.
The current behavior can be tested as follows:
1. `test1=set1; Domain=github.com` (Should Accept)
2. `test2=set2; Domain=.github.com` (Should Accept)
3. `test3=set3; Domain=github.com.` (Should Reject)
Per-browser results were:
- Chrome 94.0.4606.50 - Consistent
- Firefox: 93.0b6 - Consistent
- Safari: 15.0 (17612.1.28.5) - Didn't reject 3
Fixes #1583
> RFC 6265bis: Add domain attribute '.' prefix/suffix handling to storage model

- draft-ietf-httpbis-digest-headers.md
Rather than using Request: and Response: indications in the text, I think it looks cleaner if these are done using figure titles.  There are relatively few cross-references, but for the one that is present, this also permits anchors and references.  Please do check that I'm representing these accurately, however.
> Use titles for example messages

- draft-ietf-httpbis-priority.md
This turned out harder than I thought, because HTTP/2 bis makes a point about
deprecating some things, not talking about others and pointing people back to RFC 7540.
So if we want to target that document, without more substantial text changes, we end
up needing to tread across both lines.
This is an effort that attempts to take that approach to conclusion. It replaces
many references to "HTTP/2" with "RFC 7540". But importantly not all. The
remaining references to HTTP/2 are inteded to point to RFC-to-be HTTP/2 bis.
There's an alternative to this PR, which is to remove a lot of the text that needs to
refer to 7540. But I thought it would be interesting to see how this played out.
possibly addressed #1561
> Reorient the text to the HTTP/2bis spec

- draft-ietf-httpbis-h3-websockets.md
Tweak the phrasing of the abstract to make it a bit more clear that the document is adapting the mechanism not defining a mechanism.
Fixes #1703
> Editorial tweak to the abstract

- draft-ietf-httpbis-priority.md
RFC 7540 priorities are already deprecated.
> SETTINGS_NO_RFC7540_PRIORITIES

- draft-ietf-httpbis-priority.md
Fixes #1679.
The context here is that the document defines independent elements a) the means to deprecate RFC 7540 stream priority using a setting b) the extensible priorities scheme. This text removes conflating those elements and making it appear that Extensible priorities is mandatory.
Where someone chooses to use Extensible priorities (good choice!) there is some specific guidance about how to process settings and inform signal setting.
> don't require that extensible priorities is used

- draft-ietf-httpbis-priority.md
Fixes #1714 by taking @MikeBishop's suggestion of MAY and bolts it to an "if you can detect" caveat
> Relax requirements of NO_RFC7540 setting receiver

- draft-ietf-httpbis-priority.md
Fixes #1741.
This lets servers be more permissive if they want to treat it like the Header but allows them to be strict if they want.
Since this is not an error in the frame itself, change the code to a general error; reason phrase is available if people feel it important to share.
> Erroring on invalid Priority Field Values in frames is optional

- draft-ietf-httpbis-digest-headers.md
This editorial change combines most references to how this document relates to RFC 3230. By dropping the appendix, it makes the flow of the document more smooth, which is reflected in the ToC.
> Relocate appendix text to introduction

- draft-ietf-httpbis-priority.md
> State we are using BCP 14

- .gitignore
- Makefile
Generally, I don't think that it is a good idea to specify the use of `.SECONDARY` in makefiles as
it leaves a bunch of intermediate stuff in the repository.  It also means that you have to update
the .gitignore when you add new non-XML files.
In this case, however, the linting step in this repository ends up being very expensive and noisy as
it uses XML input.  Keeping the XML around manages that a little better.
> Keep XML files

- draft-ietf-httpbis-bcp56bis.md
- draft-ietf-httpbis-binary-message.md
- draft-ietf-httpbis-cache-header.md
- draft-ietf-httpbis-client-cert-field.md
- draft-ietf-httpbis-digest-headers.md
- draft-ietf-httpbis-expect-ct.md
- draft-ietf-httpbis-h3-websockets.md
- draft-ietf-httpbis-message-signatures.md
- draft-ietf-httpbis-priority.md
- draft-ietf-httpbis-proxy-status.md
- draft-ietf-httpbis-rfc6265bis.md
- draft-ietf-httpbis-rfc7838bis.md
- draft-ietf-httpbis-targeted-cache-control.md
- draft-ietf-httpbis-variants.md
This removes some of the customization, but I think we're good.
The only one that is special is the variants draft, which had information about implementation.
I've moved that to a section in the document.
Fixup script that I used:
```py
import fileinput, re
label = re.compile('^github-issue-label: (\S+)')
note = re.compile('^--- note_')
middle = re.compile('^--- middle')
is_note = False
for line in fileinput.input():
m = label.match(line)
if m:
print(f"""venue:
group: HTTP
type: Working Group
home: https://httpwg.github.io/
mail: ietf-http-wg@w3.org
arch: https://lists.w3.org/Archives/Public/ietf-http-wg/
repo: https://github.com/httpwg/http-extensions/labels/{m[1]}""")
elif note.match(line):
is_note = True
elif middle.match(line):
is_note = False
if not is_note:
print(line.rstrip())
```
> Add venue section to all drafts

- draft-ietf-httpbis-message-signatures.md
It looks like SHA-512 was intended here, as that is what the description and name use.
Maybe someone had in mind to add an additional rsa-pss-sha256 method.
> Fix digest in method-rsa-pss-sha512 definition

- draft-ietf-httpbis-priority.md
During IANA review of the document it was noted that the instructions for populating the new HTTP Priority Parameters registry with the urgency and incremental parameters was not that clear. So this change lists both `u` and `i` to make it clear what we want.
> clarify priority parameter registration

- draft-ietf-httpbis-priority.md
Addresses E#4b of #1802.
Bob highlights the actor is unclear. This attempts to address that in a minimal way without going too far down the rabbit hole of intermediaries.﻿
> Clarify the actor when reponses omit parameters

- draft-ietf-httpbis-priority.md
Addresses E#2a of #1802 
Bob correctly highlights that absence of a replacement might not be the only condition under which the prior signals might be used. So lets be more accurate.
> H2 priority elements might always be used

- draft-ietf-httpbis-priority.md
addresses E#4e from #1802
Bob's suggestion ﻿was isolated to one section but I think it is better to apply this to the whole document so that the terminology is conistent throughout.
> Use the full term 'priority parameters' everywhere

- draft-ietf-httpbis-priority.md
Addresses E#10a of #1802
Bob comments that the "no guidance is provided" s﻿ounds like it is in conflict with the rest of the section that includes some normative recommendations. The intent of this text was to highlight there is no (or at least very little) about how servers are supposed to combine priority parameters with the million other things that they have to worry about. 
This change shuffles the sentences around to try and make the original intent clearer.
> Tweak the server scheduling text to clarify what is covered

- draft-ietf-httpbis-priority.md
Addressed E#3a﻿ of #1802
Reference the HTTP terms we are using. Be clearer that we focus on "normal" responses and that there are other possible uses. But avoid making the entire document a piece of abstract art.
> Expand on applicability of this scheme for clarity

- draft-ietf-httpbis-priority.md
Addresses E#14b, E#14c, E#14d of #1802
This cuts some text to reduce the waffle factor ;)﻿
> trim text to focus on why e2e header

- draft-ietf-httpbis-priority.md
Addresses E#4a of #1802
﻿Although the editorial issue suggests explaining things in the priority parameters section, it seems moe useful to do so in the intro.
> slight tweak to introduction of reprioritization

- draft-ietf-httpbis-priority.md
Addresses T#12e of #1802
We don't have much evidence to quantify effectiveness. So drop that part and keep the focus purely on the considerations.﻿
> Be less assertive about retransmission

- draft-ietf-httpbis-priority.md
In Bob's TSVART review, he notes in T#2b that the mention the H2 DoS attack in Security seems useful and we should probably expand on it.
The mentions of H2 have been whittled down as 7540bis progresses and the reference to CVE-2019-9513 in the security section now seems misplaced. It's cleaner to just remove it so that the section focuses on considerations for using this document.
P.S I think this means that MT was right ;)
> Problems with HTTP/2 are not our security consideration

- draft-ietf-httpbis-priority.md
This PR proposes changes to #1803, removing redundant text.
> Remove redundant text (amends #1803)

- draft-ietf-httpbis-priority.md
Replace use of "precedence" that could be confusing with something better.
With this PR, there are still two remaining occurrences of "precedence," in [section 4.1 (Urgency)](https://httpwg.org/http-extensions/draft-ietf-httpbis-priority.html#name-urgency), and [section 8 (Merging Client- and Server-Driven Priority Parameters)](https://httpwg.org/http-extensions/draft-ietf-httpbis-priority.html#name-merging-client-and-server-d).
I think that those two are fine, as they are surrounded by other text explaining the context. I think it'd be clear to readers that we are using the term to describe *difference* of importance between multiple responses.
FIxes E#0a of #1802.
> get rid of some "precedence"

- draft-ietf-httpbis-priority.md
As discussed in https://github.com/httpwg/http-extensions/issues/1794#issuecomment-986423620, to avoid confusion, we can stop short of using phrases like "one-by-one" or "entirety," simply stating that non-incremental responses should be served in the order of the stream ID.
Addresses the original point of #1794.
> stop short of saying one-by-one, entirety

- draft-ietf-httpbis-priority.md
I'm not as good at this as @MikeBishop, but I can't help by see the obvious ones.  I saw a missing Oxford comma somewhere but I couldn't find it again when I opened the editor.
A couple of word choices are the more interesting ones: "conveyors" has a very interesting mental image associated with it.  That was awkward, but I think that "unilateral" was entirely the wrong word.
> Commas and all that

- draft-ietf-httpbis-priority.md
In #1828, @martinthomson says:
> I saw a missing Oxford comma somewhere but I couldn't find it again when I opened the editor.
I could not find missing Oxford comma, but found some others that look odd to me (as a non-native).
> "and and" and other minor nits

- draft-ietf-httpbis-digest-headers.md
Fixes #1836
There's not really any reason to describe anything other than the algorithm used and the format of encoding.
> Simplify IANA algorithm descriptions

- draft-ietf-httpbis-digest-headers.md
- remove normative text in sec
- remove TLS requirements
- rephrase insecure/collision  prone algorithms
> Fix: #1842. Remove normative text in sec & IANA.

- draft-ietf-httpbis-digest-headers.md
Fix: #1834. Remove incremental algorithms.
@LPardue tweak the text as you prefer and merge :)
> Fix: #1834. Remove incremental algorithms.

- draft-ietf-httpbis-priority.md
During IESG review, Éric Vyncke noted that the prose for the HTTP/2 PRIORITY_UPDATE frame used a type value written as `0x10` while the diagram used `10`. That inconsistency stems from 7540bis and I opened https://github.com/httpwg/http2-spec/pull/1002/files to fix that there.
While looking again at our type definition, we incorrectly stated `Type(i) = 10`. By convention, that suggest the type is a QUIC variable length integer. But that was never the intention. HTTP/2 frame type is part of the HTTP/2 frame header, which is an 8-bit field. In this draft, we are not changing the definition of HTTP/2 frame headers. Therefore the diagram is currently wrong. 
This change is editorial to address the above two issues.
> H2 PRIORITY_UPDATE type field is 8 bits

- draft-ietf-httpbis-binary-message.md
- draft-ietf-httpbis-client-cert-field.md
- draft-ietf-httpbis-digest-headers.md
- draft-ietf-httpbis-message-signatures.md
This changes the boilerplate import of bcp14 to bcp14-tagged, which now automatically scans for and marks uppercase normative words like MUST and MAY in semantically-appropriate tags.﻿
> Mark normative statements

- draft-ietf-httpbis-priority.md
I was noted that the citation to Pat Meenan's blog post lacked scientific experimental data and a decent permalink. Since we already acknowledge Pat's original scheme proposal in the acknowledgements, lets just remove this one. 
To avoid anyone picking up on a lack of multiple citations to match the multiple experiments statement, lets drop that qualifier too.
> Cite only Marx paper

- draft-ietf-httpbis-priority.md
Addressing a last call comment from @bbriscoe. 
Bob suggested s/servers/servers or intermediaries but I don't think that distinction needs to be made here because intermediaries are servers by HTTP definition.
> Servers can ignore priority signals and HTTP won't break

- draft-ietf-httpbis-priority.md
Addresses the following comment from [Benjamin Kaduk's review](https://lists.w3.org/Archives/Public/ietf-http-wg/2021OctDec/0225.html):
```
Section 4
Intermediaries can consume and produce priority signals in a
PRIORITY_UPDATE frame or Priority header field.  Sending a
PRIORITY_UPDATE frame preserves the signal from the client, but
provides a signal that overrides that for the next hop; see
Section 14.  [...]
I'm having a bit of trouble following "provides a signal that overrides
that for the next hop"; is the "that" in "overrides that" referring to
"the signal from the client"?  Is the "signal that overrides" referring
to the PRIORITY_UPDATE frame emitted by the intermediary in question?
That seems to set us up for a scenario where the same frame is both
preserving and overriding the …
```
> be clearer regarding what is preserved

- draft-ietf-httpbis-h3-websockets.md
Remove "which" from a clause where it did not belong, as per feedback from Vijay Gurbani
> Remove "which" from a clause where it did not belong

- draft-ietf-httpbis-client-cert-field.md
painful words in an attempt to explain renegotiation's applicability with client-cert header to fix #1519
> client-cert header and renegotiation

- draft-ietf-httpbis-rfc6265bis.md
> [6265bis] Specify that no decoding of Set-Cookie line should occur

- draft-ietf-httpbis-message-signatures.md
Adds text to clarify algorithms in several places:
- encode ECDSA signature as raw bytes, mark ECDSA and RSAPSS as non-deterministic
- note non-determinism of ECDSA and RSAPSS in examples, add security consideration of nondeterministic algorithms.
- Add ed25519, closes #1509
> Add Ed25519, update algorithm text

- draft-ietf-httpbis-h3-websockets.md
pseudo-header is hyphenated per [HTTP3], and expand out a
"headers" straggler.
> Editorial nits in h3-websockets

- draft-ietf-httpbis-binary-message.md
For the avoidance of doubt.
This makes encoding easier if you don't care about wasting a few bytes.
Closes #1943.
> Varints not minimal varints

- draft-ietf-httpbis-binary-message.md
Closes #1945 by using a citation rather than a redundant and wrong statement.
Closes #1944 by removing the minimum length (zero is totally fine).
> Fix field length issues

- draft-ietf-httpbis-binary-message.md
A combined "field value" is a term that HTTP defines, but we didn't link to that.  Also, the structure of this paragraph was a little more terse than it needed to be.
> Reword combining text a little

- draft-ietf-httpbis-digest-headers.md
- sf.json
This PR attempts to capture my interpretation of the discussion during the HTTP Interim meeting Feb 2022. Editorial judgement has been applied with judicious KISS.
Executive summary:
1. Obsolete 3230.
*  The suggestion was to put this in an appendix. However, if we are obsoleting Digest, I don't see much benefit in talking through many details. Stop using it and use the substitutes we spend lots of text on. The text ended up as half a page and I kept it in the Introductory section 1
2. Having a mix of sf-dictionary and sf-list that need to reference each other is really annoying. I'm sure there's a way to square the circle about using List items as lookups for Dictionary keys but after already spending hours noodling on it, it seems like an accident waiting to happen.
* So I cheated. I …
> Digest option 2.5

- draft-ietf-httpbis-digest-headers.md
- no normative text in security considerations.
Fix #1954
> Fix: #1954. No normative text in security considerations.

- draft-ietf-httpbis-message-signatures.md
The sample request (and elsewhere) use `test-key-ed25519` (one `d` not two) -- I think this was just a small type to fix!
> message-signatures: fix typo in ed25519-test-key name

- draft-ietf-httpbis-rfc6265bis.md
See #1707 for discussion and rationale.
I wasn't entirely sure where to put this new restriction, but it does seem like the UA should parse the domain attribute list and only reject the cookie if the final domain attribute contains invalid characters (as opposed to, say, reject if any domain attribute contains invalid characters). So I went with that.
> [6265bis] Require ASCII for domain attributes (fixes #1707)

- draft-ietf-httpbis-rfc6265bis.md
@johnwilander pointed out that there were use cases in which cookie expiry limits over 400 days made sense (https://lists.webkit.org/pipermail/webkit-dev/2022-January/032096.html).
> Flexibility in Cookie Expiry Timeline

- draft-ietf-httpbis-digest-headers.md
- same boilerplate text for C-Digest and R-Digest
- avoid ABNF in favor of Types
- representation-data -> representation data
- representatio-data-digest -> digests (clarified in Notational Convetions);
- integrity fields -> Integrity fields (@LPardue let me know if you meant it lowercase, it's ok to me in any way);
- digest algorithm -> hashing algorithm,
Note: it'd be cool if we could write something like
```
~~~ abnf
R-Digest = sf-dictionary
member-value = sf-binary
```
but it's ok anyway
> Fix: #1941. Editorial alignments

- draft-ietf-httpbis-binary-message.md
The HTTP/2 rules are related to field value validation, so move them there.
The rules about Connection fields are not necessary, but it won't hurt to be clearer.
Closes #1936.
> Make the field validation clearer

- draft-ietf-httpbis-binary-message.md
The format is capable of capturing messages, but the design only really supports the expression of the semantics of valid messages.  That makes it unsuitable for applications that need to know exactly what was put on the wire in a given protocol.
Closes #1937.
> This is for semantics, not forensics

- draft-ietf-httpbis-binary-message.md
The original framing might have implied that they can't be sent, where it's just that they are the
same as anything else.
Closes #1938.
> 204 responses are just like any other message

- draft-ietf-httpbis-binary-message.md
I missed this from @DavidSchinazi, but it's a point well-taken.  Not defining this was sloppy.
Closes #1944.
> Try to define lengths better

- draft-ietf-httpbis-binary-message.md
Basically, it saves the effort of writing stuff that you know to be empty.  It's
not a critical feature, but it turns out to be a simple way to deal with not
sending trailers or a body.  In the extreme, you can also drop headers to
produce the simplest and shortest HTTP message ever: 0x0140c8.
CLoses #1946.
> Why truncation

- draft-ietf-httpbis-priority.md
these are most of the changes passed back directly to us in the XML, so these changes are for posterity. I'll follow up with other PRs for other things.
The PR targets a branch `priority-auth48-all` where we will collect all the related changes before mering those back to main
> uncontroversial AUTH48

- draft-ietf-httpbis-message-signatures.md
I'm not sure what the current digest is, but it doesn't match the 23-byte HTTP body of that message.
We can verify the expected/new digest with:
```
$ echo -n '{"message": "good dog"}' | sha512sum | cut -d ' ' -f 1 | xxd -r -p | base64
mEWXIS7MaLRuGgxOBdODa3xqM1XdEvxoYhvlCFJ41QJgJc4GTsPp29l5oGX69wWdXymyU0rjJuahq4l5aGgfLQ==
```
(also verified in a go implementation of message signatures)
As the digest changed, the Signature for the ECDSA P-256 example also changed, I've included a new signature over the updated digest that verifies based on the key in the spec.
Thanks!
> message-signatures: fix Content-Digest sha-512 digest on response

- draft-ietf-httpbis-priority.md
Note: this is a test of the GitHub CI as much as anything.
kramdown-rfc2629 v 1.5.26 added the ability for non-ascii names in markdown that don't generate XML that xml2rfc would reject.
If you try this locally and see issues, try to update your tools at https://github.com/martinthomson/i-d-template/blob/main/doc/SETUP.md#update
> priority: update author name

- draft-ietf-httpbis-priority.md
Closes #2048 
rephrase multiplexing speak on H1.1 and older
> HTTP/1.1(and older)

- draft-ietf-httpbis-priority.md
Fixes #2009
This takes @MikeBishop's suggestion from the issue and turns it into a PR.
The important thing here is that even though the stream states have the same name, they operate differently depending on who is sending or receiving. Mike's text here helps make that nuance explicit. Hopefully avoiding possible confusion due to sentence proximity.
> add clarifying statements about stream state outcomes

- draft-ietf-httpbis-h3-websockets.md
> Auth48: Change references from HTTP2 => HTTP/2 and HTTP3 => HTTP/3

- draft-ietf-httpbis-priority.md
Closes #1975.
We're not in AUTH48 yet. I suggest we hold merging the change until that time.
> priority: use SF terms, not ABNF

- draft-ietf-httpbis-priority.md
Fixes #2011 
This ended up being larger than I wanted, I'm not a huge fan of that. But I think this scope of change is needed if we want to be crystal clear, even if the words I've proposed need to be tweaked.
Based on @MikeBishop's suggestion on the the issue (thanks!)
> State even more clearly intermediary unfairness

- draft-ietf-httpbis-rfc6265bis.md
> Noodle on third-party cookies

- draft-ietf-httpbis-h3-websockets.md
...and causes invalid XML to be generated as "HTTP" now appears twice as ID in the XML
> h3-websockets: title assignment "HTTP" is redundant

- draft-ietf-httpbis-digest-headers.md
-  supports current implementers of [RFC3230] in the migration to the new integrity fields
- should allow them to replace any reference to [RFC3230] with this document
Fix: #1968
> Fix: #1968. Migrating from RFC3230.

- draft-ietf-httpbis-rfc6265bis.md
Closes #1758
The spec had a note to handle trailing `.`s in the `Domain`'s value by ignoring the attribute. Since `example.com` and `example.com.` are considered distinct domains a trailing `.` should instead result in a rejected cookie. By removing this note the spec will rely on the domain matching algorithm to (correctly) reject the cookie.
> Remove note to ignore Domain attribute with trailing .

- draft-ietf-httpbis-rfc6265bis.md
Closes #2088
This is a follow up to clean up a note that https://github.com/httpwg/http-extensions/pull/2087 missed.
> Remove the trailing `.` note in 4.1.2.3.

- Makefile
- draft-ietf-httpbis-binary-message.md
Make HTTP/* informative references; fix their display.
Also, suppress some noise from xml2rfc.
> Fix references in binary messages

- draft-ietf-httpbis-rfc6265bis.md
https://github.com/httpwg/http-extensions/commit/efaa468e6af574e88152cc365deb32e262444844
introduced a change to the `cookie-octet` grammar that's completely unrelated to what the PR
actually aimed to do. This was a mistake on my part that I'll now (2 years later!) resolve.
Oops!
This addresses a portion of https://github.com/httpwg/http-extensions/issues/1073.
> [6265bis] Removing an inadvertant change to `cookie-octet`.

- draft-ietf-httpbis-digest-headers.md
Editorial change @jricher and I talked about over lunch in IETF 113.
Initially I was going to include an example of a Signature that covered content-digest, but I stepped back from doing that for a few reasons:
* the sigs draft already has a few examples that contain a content-digest
* I don't want to have to explain all the items or concepts that appear in HTTP signatures examples, that belongs in the sigs draft itself and we shouldn't duplicate it
* we probably aren't running the same infrastructure to make sure the examples stay correct
What might work is for the sigs doc to provide some slimmed-down examples that focus on signing `Content-Digest` and `Repr-Digest` and then we could reference them from this draft. But I'm open to other ideas.
> Mention HTTP Message Signatures as an illustration

- draft-ietf-httpbis-client-cert-field.md
try to say that for multiple post-handshake client certificate authentications, only use the last one (to fix #1923)
> use just last of multiple post-handshake client cert authentications

- draft-ietf-httpbis-message-signatures.md
This updates the document to comply with the style guides:
- clean up structured field references and remove ABNF
- format field names per style guide
- update semantics and messaging references
- udpate self-references
- update registry tables
This does not (yet) modify the registry initial contents from tables to dictionary lists because I'm not sure how to format those for adding multiple 
entries at once.
> Document Style updates for Signatures

- draft-ietf-httpbis-digest-headers.md
These are used to bootstrap the registry in IANA. Digest Fields themselves don't have normative requirements on the algorithms.
> convert algorithm refs to informative

- draft-ietf-httpbis-origin-h3.md
Drops the accidentally-empty Section 2, but should otherwise match the adopted draft.
> Add H3 ORIGIN draft

- draft-ietf-httpbis-digest-headers.md
All very straightforward, except the reference to obsoleted RFC 2818. mnot suggest we need to point to RFC 9110 but the intent of the text is speaking about TLS records, so lets just point at TLS directly.
Closes #2151
> Use the HTTP core RFCs. Twiddle with some other refs.

- draft-ietf-httpbis-rfc6265bis.md
Closes #1881
Cookie attribute names are case insensitive, this PR adds a note saying as much.
> RFC6265bis: Add case insensitivity note to Set-Cookie Syntax

- draft-ietf-httpbis-rfc6265bis.md
Closes #1502
During the [Sept 2021 Interim meeting](https://notes.ietf.org/notes-httpbis-21-09#Issue-1502---Better-specify-serialization) it was decided that this note should be removed and that another spec (perhaps HTML) can handle it.
> RFC6265bis: Remove note regarding cookie serialization

- draft-ietf-httpbis-digest-headers.md
- fix #2180
- clarifies that C-L only specifies whether R-Digest can be associated to other resources
- move info on 204 to PATCH, where it was intended (see https://datatracker.ietf.org/doc/html/rfc5789#section-2.1)
> Fix: #2180. Clarify POST and C-L.

- draft-ietf-httpbis-message-signatures.md
This adds a binary wrapper for fields that don't follow the List or Dictionary format for multiple values, such as Set-Cookie. The wrapper is selected 
using the `bs` parameter, and the component value is made by wrapping each individual field value in a Byte Sequence and putting them into a List, then 
doing a strict serialization on those values.
Closes #2166
> Wrapping problematic fields for signatures

- draft-ietf-httpbis-rfc6265bis.md
Closes #1418
This adds a note clarifying that cookies whose domain was added to the PSL should not be sent even if they domain match the URI's host.
For example.
`Set-Cookie: foo=bar; Domain=example.com`
If example.com is added to the PSL then `foo` should not be sent to sub.example.com nor example.com
> RFC6265bis: Add note not to send invalid cookies due to PSL changes

- draft-ietf-httpbis-rfc6265bis.md
Closes #1210
While already discouraged by the grammar, this warning further discourages servers from sending nameless cookies which have a history of causing compatibility problems.
It also reorders the notes in the syntax section to group similar notes together.
> RFC6265bis: Add warning that servers should not send nameless cookies

- draft-ietf-httpbis-rfc6265bis.md
Closes #1288
This changes how 6265bis computes the Site for Cookies for Service Workers by referring to their spec instead of spelling it out locally.
It's been some time since this was [last discussed](https://notes.ietf.org/notes-httpbis-21-09#Issue-1288---Service-Workers) so while I think this was the agreed upon change I may be mistaken.
> RFC6265bis: Offload Service Worker SFC computation to spec

- draft-ietf-httpbis-message-signatures.md
Adds an optional `context` parameter to signatures, to allow applications to signal specific usage between the signer and verifier.
Closes #2133
This PR does not add this to any examples yet, but we probably should if accepted.
> Add signature context

- draft-ietf-httpbis-resumable-upload.md
This PR adds the draft for Resumable Uploads. I haven't yet released a `-00` version (as indicated in https://github.com/httpwg/http-extensions/blob/main/SUBMITTING.md#submitting-a-draft-revision), as I wanted to ensure that everything in the document is alright first.
> Add Resumable Uploads draft

- draft-ietf-httpbis-rfc6265bis.md
Closes #2231
Some servers are case-insensitive with cookie names which can lead to
security problems when a server assumes that cookie prefixes are too.
This PR instructs UAs to process prefixes case-insensitively to
compensate.
> RFC6265bis: Compare cookie name prefixes case-insensitively

- draft-ietf-httpbis-resumable-upload.md
In the present document, there are two "Appendix" sections that sandwich the acknowledgements. More standard would be have acknowledgement after appendices, and have the appendix sections numbered.
> shuffle appendices a little

- draft-ietf-httpbis-origin-h3.md
Fixes #2161.  Editorial, since this is merely restating locally what was previously incorporated by reference.
> Explicitly state layout of ORIGIN frame

- draft-ietf-httpbis-client-cert-field.md
client-cert: Mention that origin server access control decisions can be conveyed with a 403 or by selecting response content
#1935
> client-cert: Mention that origin server access control decisions can be conveyed with a 403 or by selecting response content

- draft-ietf-httpbis-rfc6265bis.md
Modify the cookie storage algorithm to reject cookies that:
- Do not have a name
- Have values that look like cookie prefixes
As mentioned in #2229, malicious servers can exploit nameless cookies to impersonate prefix'd cookies.
> RFC6265bis: Prevent nameless cookies with prefixed values

- draft-ietf-httpbis-client-cert-field.md
> client-cert: HTTP Semantics now a normative ref

- draft-ietf-httpbis-client-cert-field.md
and use "describes" rather than "standardize" to better align w/ the Informational intended status
> lose the aspiration for #2282

- draft-ietf-httpbis-client-cert-field.md
Attempt to reword the 'Header Block Size' section to use more HTTP version neutral terms (for #2288)
> reword 'Header Block Size' section

- draft-ietf-httpbis-digest-headers.md
And how users of digests are the ones responsible for deciding what to
do if something is ignore.
Fixes #2382
> Expand on how integrity preferences can be ignored

- draft-ietf-httpbis-origin-h3.md
@fpalombini
Adds the BCP14 boilerplate in a Notation Conventions section. As part of that, I noticed we don't reference any explanation of the frame layout language used -- it's the same used in QUIC and HTTP/3 -- so I added an RFC 9000 ref to pick that up in the same section.
> Add boilerplate

- draft-ietf-httpbis-message-signatures.md
Collects editorial comments of AD-reviewed signatures draft.
Closes #2371
Closes #2364
Closes #2368
Closes #2333
Closes #2330
> AD Review of Signatures (Editorial)

- draft-ietf-httpbis-message-signatures.md
Clarify method case requirements. Add justification for use of empty query string.
Closes #2363
Closes #2329
> Clarify Derived Components

- draft-ietf-httpbis-message-signatures.md
Changes the reference to HTMLURL to use one of the newly-registered permanent anchors. Previously two different section anchors had been used, but I'm not sure how to put 
both of them into the references section. Is there a syntax for multiple target URLs?
Closes #2370
> Fix HTMLURL reference

- draft-ietf-httpbis-resumable-upload.md
The current draft -00 of the resumable upload protocol uses a client-generated token to identify which procedures belong together. There has been valid criticism of this methodology, especially that the server is not able to control this identifier, which fits badly into the typical request-response schema of HTTP APIs. There seems to be a majority supporting the use of server-generated identifiers over client-generated ones.
That being said, the original intention of these tokens was two-folded and is still desirable:
1. Allow clients to upload small files in a single request, without the need of additional roundtrips.
2. Allow clients to resume an upload before receiving a response for the server by using the client-generated token.
We believe it is possible to achieve these two goals …
> Proposal of server-generated upload URLs

- draft-ietf-httpbis-client-cert-field.md
AD review feedback (thread at https://lists.w3.org/Archives/Public/ietf-http-wg/2023JanMar/0088.html) and some minor editorial updates
> client-cert: AD review feedback 

- draft-ietf-httpbis-unprompted-auth.md
As requested [on list](https://lists.w3.org/Archives/Public/ietf-http-wg/2023JanMar/0139.html) after document adoption.
Note: In the markdown I've listed the label as `unprompted-auth`, please create the label before merging this PR.
> Add draft-ietf-httpbis-unprompted-auth

- draft-ietf-httpbis-resumable-upload.md
The Upload-Incomplete header is now required for all Upload Creation Procedures and was missing from this example. It is not mandatory for Upload Appending Procedure requests, so I didn't add it to its example of a PATCH request. @guoye-zhang do you still think the header is missing somewhere else?
> Add missing Upload-Incomplete header

- draft-ietf-httpbis-resumable-upload.md
I think this PR corrects the changelog a bit, which was missing the entry for draft-ietf-httpbis-resumable-upload-00. This version was the same as draft-tus-httpbis-resumable-uploads-protocol-02 but published under a new name (with no changes to the content).
> Correct changelog in resumable-upload

- draft-ietf-httpbis-digest-headers.md
With Digest, the encoding of the digest value was based on the digest
algorithm. For different algorithms, this varied between base64, hex
encoding or decimal encoding.
In this spec, we removed the variablilty by using SF Byte Sequence,
which is always serialized as a base-64 encoding of the input bytes. All
algorithms are now expected to use this format.
This change tries to make it more clear that we expect the input of the
Byte Sequence to be. For example, we really don't want people accidentally
base-64'ing the textual hex represenation output of cksum - that can
lead to interop pain.
To help implementers further, add a new appendix with some samples that
can be used as test vectors.
Closes #2385
> Clarify that hashing bytes are base-64 encoded and give examples

- draft-ietf-httpbis-digest-headers.md
Murray suggested some things that we could change about the way new IANA
registry was being handled. This change:
* tries to make it clearer that this document uses a new registry that
we will need IANA to create
* moves rote IANA instructions to the IANA considerations
* better highlights interesting hash algorithm considerations for
implmenters
* clarifies the registration procedure and expands on the expectations
for the Designated Expert(s)
> Apply AD suggests WRT to Hash Algorithm registry

- draft-ietf-httpbis-digest-headers.md
- some content-coding are "not deterministic" ;)
- not only encryption-related ones.
Fix #2384
> Fix: #2384. Non-deterministic content coding beyond encryption.

- draft-ietf-httpbis-digest-headers.md
By virtue of the presentation formats available to RFCs, it was ambigous
to readers whether example's content included a trailing LF or not. This was bad
because the content (or even representation) is required for digest
calculation.
This change makes it clear, where needed, what the object bytes are that
we are sticking into the digest calculation. And since that now includes
LF, we need to recompute all the example digest values.
Fixes #2388
> Message contents has newlines, ensure digest consistency

- draft-ietf-httpbis-sfbis.md
> Discuss limitations on types based on field def

- draft-ietf-httpbis-unprompted-auth.md
Add requirement for unprompted auth to use TLS 1.2 with extended master secret or later.
Fixes httpwg/http-extensions#2441
> Require modern TLS

- draft-ietf-httpbis-unprompted-auth.md
> Unprompted auth: replace u with k

- draft-ietf-httpbis-message-signatures.md
A signature over another signature does not provide the transitive protection that it seems it should. The examples and advice have been updated to accomodate this.
> Update advice and examples on signing signatures

- draft-ietf-httpbis-rfc6265bis.md
Closes #2289
As mentioned in #2289, I've seen a few instances where an implementer chose the wrong section for their needs which caused compatibility issues down the line.
This PR adds a section that will (hopefully) grab the reader's attention and direct them to the correct section.
> RFC6265bis: Advise the reader which section to implement

- draft-ietf-httpbis-digest-headers.md
Follow up to the IANA review of the digest spec. We asked them to deprectae the old registry, so lets add a note to it to clarify what the new expectations of that registry are.
> Update IANA note on old registry

- draft-ietf-httpbis-message-signatures.md
Reframe use cases that had previously signed signature values to avoid problems with this approach.
> Reframe signing signatures

- draft-ietf-httpbis-sfbis.md
Right now the `sf-date` nonterminal is (presumably unintentionally) orphaned.
> sfbis: Fix ABNF to include sf-date in bare-item

- draft-ietf-httpbis-sfbis.md
There are currently some uses of "serialise" in place of the far more common "serialize", including one case that breaks the pattern of header names ("Seriali**z**ing a List", "Seriali**z**ing a Dictionary", "Seriali**z**ing an Item", …, "Seriali**s**ing a Date").
This PR also includes an analogous update of "summarises" to "summarizes" to increase the general pattern of American spellings.
> sfbis: Uniformly use American spellings

- draft-ietf-httpbis-message-signatures.md
Point out that many frameworks smush together form parameters and query parameters into one bucket, and that can cause unexpected shadowing.
Some examples changed to avoid ambiguity.
> call out query parameter handling oddities

- draft-ietf-httpbis-rfc6265bis.md
Closes #2474
Add "top-level navigation" to the list of defined terms.
This CL has a dependency on https://github.com/httpwg/http-extensions/pull/2480
> RFC6265bis: Define top-level navigation

- draft-ietf-httpbis-rfc6265bis.md
Closes #2372
The HTML spec recommends avoiding using "browser contexts" and instead recommends "navigables".
This PR refactors rfc6265bis to use "navigables".
> RFC6265bis: Use navigables concept

- draft-ietf-httpbis-digest-headers.md
In a few places we link to HTTP Section 3.2, which doesn't do the best
job of defining representation data. 8.1 is a better section for that.
> Link to HTTP Section 8.1 when talking about representation data

- draft-ietf-httpbis-unprompted-auth.md
> Remove HMAC and switch to Authorization

- draft-ietf-httpbis-digest-headers.md
During the SEC AD review, a DISCUSS was raised about the current status
values.
This change modifies the values to better align with Signatures. The
guidance for registration and/or usage of an algorithm based on the
status is not affected.
> Rename algorithm registration status values

- draft-ietf-httpbis-sfbis.md
> All percent encoding

- draft-ietf-httpbis-alias-proxy-status.md
Allow the original name of the next hop to be the start of the list, and add an example.
Closes #2600
> Allow original name in alias list

- draft-ietf-httpbis-digest-headers.md
- fixes #2613 
- removes redundant IANA url
> Fix: #2613. Typo in IANA notes

- draft-ietf-httpbis-compression-dictionary.md
This is the -00 draft of the compression-dictionary ID.  I used the resumable-upload.md draft as a template for the metadata fields at the top of the document so hopefully they are correct for an IETF-standards track draft.
> Added the compression-dictionary draft

- draft-ietf-httpbis-resumable-upload.md
This follows form where the changelog is put at the end of the file and marked for removal when the RFC is published. The reason being that the log is useful for implementers during standardization but not post RFC. 
Removing the section should avoid changing Appendix values of other sections, so it moves to the end of document.
> Tweak resumable appendix

- .gitignore
- draft-ietf-httpbis-resumable-upload.md
- package.json
@martinthomson this works but generates warnings. Am I holding it wrong?
> /home/lucas/workspace/http-extensions/draft-ietf-httpbis-resumable-upload.xml(92): Warning: Found SVG with width or height specified, which will make the artwork not scale.  Specify a viewBox only to let the artwork scale.
/home/lucas/workspace/http-extensions/draft-ietf-httpbis-resumable-upload.xml(152): Warning: Found SVG with width or height specified, which will make the artwork not scale.  Specify a viewBox only to let the artwork scale.
/home/lucas/workspace/http-extensions/draft-ietf-httpbis-resumable-upload.xml(191): Warning: Found SVG with width or height specified, which will make the artwork not scale.  Specify a viewBox only to let the artwork scale. …
> Upgrade resumable diagrams to SVG

- draft-ietf-httpbis-resumable-upload.md
See https://httpwg.org/admin/editors/style-guide.
Lots of boring editorial tweaks to ensure better consistency both
within the document and other HTTP specs.
> Editorial changes mainly for style guide alignment

- draft-ietf-httpbis-resumable-upload.md
Since the last draft version was published, we replaced the `Upload-Incomplete` header with the `Upload-Complete` header. This requires an increase in the interop version as existing clients will need changes to be compatible with the next draft release.
> Increase draft interop version

- draft-ietf-httpbis-sfbis.md
> Require supported Date ranges

- draft-ietf-httpbis-alias-proxy-status.md
> Add reference to RFC3493

- draft-ietf-httpbis-compression-dictionary.md
This switches the custom wildcard matching to use [URLPattern](https://wicg.github.io/urlpattern/) with regexp support disabled. URLPattern is being used by the service worker routing API's and is what the web side is standardizing on for anything that pattern-matches URLs.
This splits the match pattern into explicit path and search (query param) components and forces the origin to be inherited from the dictionary request URL.
Also included here is a new `Use-As-Dictionary` field for `match-dest` to allow for matching on request destinations. The biggest use case for that will be for allowing site-wide HTML dictionaries to do something like `Use-As-Dictionary: match-path="/*", match-dest="document"` and for the dictionary to not be sent for every request across the site (images, etc).
See …
> Switch to URLPattern for request matching

- draft-ietf-httpbis-compression-dictionary.md
Discussion at IETF 118 was that the `ttl` didn't necessarily need to be short to reduce variations (was originally planning on 7 days) but chaning it to last-fetched instead of last-written is important. This updates the default `ttl` to 14 days as a balance (can always be overridden explicitly).
> Switch the default ttl to 14 days since last fetched

- draft-ietf-httpbis-sfbis.md
Not pretty, but alternatives do not look better (maybe create an extra production for the stuff between DQUOTEs?)
> sfbis: abnf for displaytring too wide - wrap it (fixes #2677)

- draft-ietf-httpbis-compression-dictionary.md
Adds a new "Content-Dictionary" with the hash of the dictionary used when encoding the HTTP response.
For #2636
> Add the dictionary hash to the HTTP response

- draft-ietf-httpbis-compression-dictionary.md
`search` is the name used by `URLPattern` which is what the value is mapped to.
> Changed dictionary match-query to match-search

- draft-ietf-httpbis-compression-dictionary.md
This adds support for a server-provided sf-string "id" of up to 1024 characters that is echoed back in a "Dictionary-ID" request header when the dictionary is advertised as being available.
This allows for a server to use something other than the hash to retrieve the dictionary (i.e. a cache key). This should be more flexible than the client sending the original request URL and will allow for servers to store arbitrary context information with the dictionary.
It doesn't open up any additional privacy or security concerns because the dictionary hash was already being treated as if it was user-identifiable information.
For #2633
> Add support for a server-provided dictionary ID

- draft-ietf-httpbis-resumable-upload.md
As brought up in #2681, resumable uploads may interfere with intermediaries scanning the request content. This PR adds a paragraph in the security considerations.
Closes https://github.com/httpwg/http-extensions/issues/2681.
> Add security consideration regarding request filtering

- draft-ietf-httpbis-resumable-upload.md
- sf.json
This PR
- switches the example message to HTTP/1.1 notation as recommended in the style guide (https://httpwg.org/admin/editors/style-guide#example-messages).
- fills a missing change from #2664 into the changelog.
- corrects to spelling mistakes.
> Editorial changes to resumable upload draft

- draft-ietf-httpbis-compression-dictionary.md
1. Not needed
2. Would need to be at title, not label-like
> compression-dictionary: remome abbreviated title

- draft-ietf-httpbis-compression-dictionary.md
It needs to be self-contained (would be changed by RFC Editor anyway)
> compression-dictionary: remove links from abstract

- draft-ietf-httpbis-compression-dictionary.md
This removes the dictionary-specific ttl and switches to using the dictionary resource freshness as the mechanism for expiring dictionaries.
Fix #2649
> Removed ttl from dictionary response

- draft-ietf-httpbis-compression-dictionary.md
This treats empty dictionary strings as the same as there being no dictionary and reqires all ID's have a non-zero length for the Dictionary-ID header to be sent.
Fix #2721
> Treat empty dictionary ID's as "no ID".

- draft-ietf-httpbis-compression-dictionary.md
This changes the `match-dest` field to be a list of destination strings to allow for matching multiple destinations (i.e. document and frame).
This allows for matching an empty destination explicitly using an empty string. e.g. `("script" "")`
Fix #2722
Fix #2723
> Change dictionary match-dest to a list of strings

- draft-ietf-httpbis-compression-dictionary.md
Switched from using the ABNF field types to the human names (i.e. sf-dictionary to Dictionary) for all of the Structured Field header values.
Switched dictionary "type" to a Token (from String).
Fix #2731
> Switch away from using ABNF names for field types

- draft-ietf-httpbis-resumable-upload.md
A server might allow GET requests to be sent to an upload resource and serve content, in which case a 200 status code is more appropriate for responses to HEAD requests. This PR lifts the requirement that a successful response must be a 200.
Closes #2662.
> Resumable Upload: Allow 200 in response for retrieving offset

- draft-ietf-httpbis-resumable-upload.md
#2745 allows another status code to be returned for offset retrieval requests. This might break interoperability between existing implementation, so this PR bumps the interop version to make this change more visible.
> Resumable Uploads: Bump interop version

- draft-ietf-httpbis-rfc6265bis.md
Fixes #2541
Technologies such as HTTP/2 will split the `cookie` header into multiple fields. This PR modifies the spec to no longer expressly forbid this and instructs servers to be aware and capable of handling multiple incoming `cookie` headers.
> Refactor cookie header text

- draft-ietf-httpbis-rfc6265bis.md
Closes #2644
Adds some additional notes and warnings to developers on how to more carefully use SameSite cookies.
> Add additional developer warnings for SameSite cookies

- draft-ietf-httpbis-rfc6265bis.md
Closes #2104
This PR removes the requirement of checking the request's redirect chain during the computation of same-site-ness.
This is being done because RFC6265bis is blocked by this work but we have yet to find a way to implement it in a web compatible way. In the interest of moving RFC6265bis forward the requirement is being removed.
> Remove consideration of same-site redirect chain

- draft-ietf-httpbis-compression-dictionary.md
This change makes it explicit that the `zstd-d` content encoding is `Zstandard with up to a 8 MB compression window` (same as `zstd`) and `br-d` is `Brotli with up to a 16 MB compression window` (same as `br`).
See the discussion in #2754 for why larger ZStandard values were not selected.
This carries some nuance for what encoding to use when compressing for maximum benefit as the resource size crosses beyond 8 MB but that is more of an editorial discussion about the individual compression algorithms and probably better laid out in blog posts or explainers than in the spec.
Fix #2754
> Specify the compression window sizes for zstd-d and br-d

- draft-ietf-httpbis-secondary-server-certs.md
Initial commit of `draft-httpbis-secondary-server-certs`, as requested [on list](https://lists.w3.org/Archives/Public/ietf-http-wg/2024JanMar/0151.html) after document adoption.
Please create the label `secondary-server-certs`, as I have added in the markdown. Thanks!
> Add draft-httpbis-secondary-server-certs

- draft-ietf-httpbis-compression-dictionary.md
This changes the maximum ZStandard compression window to be the larger of 8 MB and the size of the dictionary. This allows for clients to limit the maximum window size to as low as 8 MB if they like (by not advertising `zstd-d` support) while also allowing for clients to use larger dictionaries with ZStandard than they would be able to if the global limit was 8 MB.
Fix #2754
> [compression-dictionary] Allow for larger ZStandard compression windows.

- draft-ietf-httpbis-compression-dictionary.md
This adds the definition for the `compression-dictionary` link relation type and relevant IANA registration information.
The link relation provides a way to trigger the fetch of a stand-alone dictionary (e.g. for compressing HTML). The actual dictionary processing follows the standard path and headers once the fetch has been initiated.
There is discussion in issue #2772 as well as a [related issue](https://github.com/whatwg/html/issues/10162) in the HTML spec.
In Chrome's current origin trial and the initial explainers this is the `dictionary` relation type but that term is too generic for this specific case.
Fix #2772
> [compression-dictionary] Added link relation

- draft-ietf-httpbis-compression-dictionary.md
This eliminates the `Content-Dictionary` response header and moves the hash of the dictionary into the payload of the response.
Specifically, it adds 36-byte header in front of the compressed stream which is a 4 or 8-byte signature followed by the 32-byte SHA-256 hash digest.
The signature is different for the two different compressions:
* Dictionary-Compressed Brotli: `\xFF\x44\x43\x42` (0xFF followed by `DCB`)
* Dictionary-Compressed Zstandard: `\x5e\x2a\x4d\x18\x20\x00\x00\x00` (32-byte skippable Zstandard frame)
This also changes the content-encoding names for the different schemes to make it clear that they are a new format and not a raw brotli or Zstandard stream (`dcb` and `dcz`).
From the cli, the stream is equivalent to:
```sh
echo -en '\xffDCB' > data.txt.dcb && \
openssl dgst …
```
> [compression-dictionary] Moved the dictionary hash into the body

- draft-ietf-httpbis-compression-dictionary.md
This simplifies the CORS processing language in the doc, leaving all of the client-side readability processing to fetch and clearly spelling out the server responsibilities.
Fix #2634
> [compression-dictionary] Tightened up the CORS language

- draft-ietf-httpbis-rfc6265bis.md
Closes #2789
Moves the user agent instructions out of the, non-normative, server sections.
> Refactor Cookie Expiration Limits

- draft-ietf-httpbis-rfc6265bis.md
Closes #2794
HTTPSEM has been published as RFC9110, update all reference to reflect this.
> Update HTTPSEM to RFC9110

- draft-ietf-httpbis-zstd-window-size.md
Initial commit of `draft-httpbis-zstd-window-size`, as requested [on list](https://lists.w3.org/Archives/Public/ietf-http-wg/2024AprJun/0079.html) after document adoption.
Please take a look. Thank you!
> Add draft-ietf-httpbis-zstd-window-size

- draft-ietf-httpbis-compression-dictionary.md
This makes it clear that the `dcb` and `dcz` content encodings are for "raw" dictionary types only.
> [compression-dictionary] Explicitly link the content encodings to raw dictionary types

- draft-ietf-httpbis-rfc6265bis.md
Closes #2796
Closes #2797 
Adds suggestions for how servers could fulfill the `MUST be tolerant of multiple cookie headers` requirement
Adds suggestion that servers be mindful of the number and size of the cookies they set to avoid hitting their own header length limits. Also mention that UA should consider splitting longer fields.
> Add multiple cookie header tolerance suggestions & length limit warnings

- draft-ietf-httpbis-resumable-upload.md
[RFC 9457](https://datatracker.ietf.org/doc/html/rfc9457) defines a framework for problem types, which can be used as a standardized response format when errors occurs. With resumable uploads, we have a few cases where such problem types could be useful, but usage remains entirely optional.
The text in this PR has been inspired by similar sections from [RFC 9458](https://www.rfc-editor.org/rfc/rfc9458.html#name-registration-of-date-proble).
> Resumable upload: Problem Types

- draft-ietf-httpbis-resumable-upload.md
This is a follow-up to #2811, which defined a problem type for when the server rejects modification for an completed upload. However, the draft didn't specify that such modifications are not allowed. This PR adds this requirement.
The section for offset retrieval already includes a definition for when an upload is complete, so this is not repeated in this PR's changes:
> An upload is considered complete only if the server completely and successfully received a corresponding creation request ({{upload-creation}}) or append request ({{upload-appending}}) with the `Upload-Complete` header value set to true.
> Resumable Upload: Completed uploads must not be appended to

- draft-ietf-httpbis-resumable-upload.md
https://github.com/httpwg/http-extensions/pull/2743 made the use of `application/partial-upload` media type mandatory for appending to an upload. This warrants a new interop version.
> Resumable Upload: Bump interop version

- draft-ietf-httpbis-rfc6265bis.md
minimalist attempt at a fix for #2791
> Tweak the example in the explanation of "Lax-allowing-unsafe"

- draft-ietf-httpbis-compression-dictionary.md
This makes it clearer what standard is being depended on, while still deep-linking to the right section of that standard.
This generates citations like "see [Part RequestDestination](https://fetch.spec.whatwg.org/#requestdestination) of [[FETCH](#FETCH)]". The "RequestDestination" part is free text in the `section` attribute. I don't see a way to change the "Part" text. We can use the [`sectionFormat` attribute](https://authors.ietf.org/references-in-rfcxml#referring-to-a-section-in-another-document-such-as-another-rfc) to rearrange it to "see [[FETCH](#FETCH)], [Part RequestDestination](https://fetch.spec.whatwg.org/#requestdestination))" if y'all prefer.
> [compression-dictionary] Use <xref section> to avoid needing a new reference for each deep link.

- draft-ietf-httpbis-safe-method-w-body.xml
Okay, this recovers the commits that were previously in #2851 and have been manually reverted by @reschke in 8dec5fc1cdc45adbb33238dddf63382b38d158bd.  We can close #2852 and work here until we're ready to merge. Sorry for the thrashing.
> QUERY and (Content-)Location Again

- draft-ietf-httpbis-no-vary-search.md
This has been adopted by the working group as of Sept 25, 2024, after previously existing at:
https://github.com/jeremyroman/http-no-vary-search
https://github.com/WICG/nav-speculation
> Add draft-ietf-httpbis-no-vary-search

- draft-ietf-httpbis-resumable-upload.md
- splits C-E and T-E sections
- clarifications quoted from HTTP and MESSAGING
- link to DIGEST-FIELDS appendix
Fix: #2880 
This PR contains some quotes from HTTP and MESSAGING. While they can be redundant, the previous wording made me think that they were not.
> Fix: #2880. Split Content-Encoding and Transfer-Encoding sections.

- draft-ietf-httpbis-resumable-upload.md
This change allows client to discover support for resumable uploads and potential limits via an OPTIONS request.
Closes https://github.com/httpwg/http-extensions/issues/2833.
A brief comment on this sentence:
> The limits announced in an `OPTIONS` response SHOULD NOT be less restrictive than the limits applied to an upload once the upload resource has been created.
Once the server has created an upload resource it might have more information available (user details, file metadata etc) and apply different limits than it would have known upfront for an OPTIONS request where this information was not available. We allow this difference but recommend that the upfront announced limits are not looser than the limits after the upload resource has been created. The client can then assume that it …
> Resumable Upload: Discover upload limits through OPTIONS request

- draft-ietf-httpbis-resumable-upload.md
The definition of upload creation requests allows the client to include the entire file, some file data or no data at all. While we provide this flexibility, we don't give guidance on when which approach is best suited.
This PR adds this missing piece and explains how an optimistic client can attempt to upload the file in one request and how a careful client uses a separate request for creating the upload. In addition, it also mentions how to transparently upgrade to resumable uploads, which wasn't explained in detail before.
Let me know if you have any feedback on this.
> Resumable Upload: Add guidance on upload creation strategy

- draft-ietf-httpbis-optimistic-upgrade.md
This avoids having to determine whether `HTTP/*.*` is an actual existing standard or not.
This is an alternative to #2818
Fixes #2737
> [optimistic upgrade] Remove mention of HTTP/*.*

- draft-ietf-httpbis-optimistic-upgrade.md
This includes changing the title, adjusting the language to be more generic, and adding a section with guidance for HTTP CONNECT.
Fixes #2817
> [optimistic-upgrade] Extend the draft to cover HTTP CONNECT

- draft-ietf-httpbis-optimistic-upgrade.md
> [optimistic-upgrade] Recommend GET for future Upgrade Tokens

- draft-ietf-httpbis-safe-method-w-body.xml
A minor typographical fix and slight rephrasing of limitations of current query-embedded-in-request-URI method.
> query: Editorial changes to Introduction

- draft-ietf-httpbis-optimistic-upgrade.md
> [optimistic-upgrade] Clearly limit recommendations to HTTP/1.1

- draft-ietf-httpbis-rfc6265bis.md
Closes: #2938
Closes: #2963
Adds an example to the Examples section to clarify and illustrate that cookie names are case-sensitive.
Additionally adds a clarification that cookie names could be empty to improve readability.
> Clarify that cookie names are case-sensitive and may be empty

- draft-ietf-httpbis-rfc6265bis.md
Clean up leftover, incorrect, and obsolete references.
Also adds `submissiontype: IETF` explicitly, this was previously automatically applied.
> Clean up editorial issues

- draft-ietf-httpbis-rfc6265bis.md
The previous PR, #2972, removed the only usages of some references, this one cleans them up.
Additionally cleans up some non-essential non-ascii characters.
> Clean up unused references and non-ascii characters

- draft-ietf-httpbis-rfc6265bis.md
Closes #2974
Make every use of "case-sensitive" hyphenated.
> Standardize on "case-sensitive"

- draft-ietf-httpbis-rfc6265bis.md
Fixes httpwg/http-extensions#2981
> [RFC6265bis] Editorial: drop a non-normative "should".

- draft-ietf-httpbis-rfc6265bis.md
Closes #2982
Adds RFC8446 (TLS) as an informative reference and links to it where references are made
> Add TLS as an informative reference

- draft-ietf-httpbis-rfc6265bis.md
This patch shifts several recommendations in Section 4's definition of a well-behaved `Set-Cookie` profile from SHOULD to MUST. This change makes server requirements less ambiguous, but does not change Section 5's definition of clients' obligations to gracefully handle servers' errors.
Closes httpwg/http-extensions#2980.
> [RFC6265bis] Harden requirements for the `Set-Cookie` profile.

- draft-ietf-httpbis-resumable-upload.md
The current draft mixes the use of _representation (data)_, _file_, or just _data_ when referring to the bytes being uploaded. This inconsistency is confusing and the use of _file_ is not entirely correct because resumable uploads can transfer non-file representations as well, as was rightfully [mentioned by Roy Fielding on the mailing list](https://mailarchive.ietf.org/arch/msg/httpbisa/m-iXTJQGdb8XpxGjZWxXGj6Siic/).
This PR attempts to unify the terminology and embrace the HTTP terms _representation_ and _representation data_ where possible.
> Resumable Upload: Correct terminology around representations

- draft-ietf-httpbis-resumable-upload.md
The current draft defines some references on the top, while others are defined inline. This PR removes the inline references and replaces them by the corresponding definitions in the head section.
> Resumable Upload: Remove inline references

- draft-ietf-httpbis-resumable-upload.md
RFC 9110 uses "interim response" throughout and intermediate is confusingly similar
looking to intermediary, which is something entirely different.
I didn't touch the appendix instances, since those are getting axed anyway.
> s/intermediate response/interim response

- draft-ietf-httpbis-resumable-upload.md
The current draft includes four appendices that are not needed anymore as their content is either covered by other sections of the document or not relevant anymore:
1. "Informational Response" included a brief discussion of the pros and cons of using informational response, which can also be found in the section about upload strategies. I moved one sentence about waiting for a 104 there as well.
2. "Feature Detection" listed different approaches for discovering server-side support. We have now settled on using informational responses for this and the appendix is no longer relevant.
3. "Upload Metadata" explained how representation metadata can be included in a resumable upload. This is already covered in the upload creation section.
4. "FAQ" explained that multipart uploads can also be …
> Resumable Upload: Remove appendices

- .github/CODEOWNERS
- .gitignore
- draft-ietf-httpbis-incremental.md
This is a direct copy from https://github.com/kazuho/draft-kazuho-httpbis-incremental-http/blob/db3b05696db34eb18cafc4947f5c21cdaff7e032/draft-kazuho-httpbis-incremental-http.md with just the `docname` changed.
I removed the extra "-http" from the name and ran `make update-codeowners` which seems to have also updated the `.gitignore` (that's emergent behaviour that surprised me a little, even though I think that it is correct to do so).
> Incremental draft

- draft-ietf-httpbis-rfc6265bis.md
We used two different names for the attribute name registry this document asks IANA to create. This PR normalizes them to "Cookie Attributes" and clarifies the name.
> [RFC6265bis] Clarify IANA considerations.

- draft-ietf-httpbis-resumable-upload.md
This PR tries to improve the draft's readability by introducing a dedicated section about the upload resource. This resource is the main component that enables resumable uploads but is not directly described in the document so far. Additionally, some of the section in the current draft are too long and would benefit from being broken up.
The new section about the upload resource houses a brief description of its responsibilities and the state that the resource needs to keep track of (offset, completeness, length, limits). I also moved the definition of the corresponding headers (Upload-Offset etc) in there as it made sense to me to describe the values and their presentations in the same space. Let me know if you disagree here.
The upload resource section then includes the definition of …
> Resumable Upload: Upload Resource Section

- draft-ietf-httpbis-resumable-upload.md
Closes #2940.
The Upload-Limit header can provide the remain lifetime of the upload resource in number of seconds under the `expires` key. However, this name is misleading as it implies that the value is an absolute timestamp. A better name could be `max-age`, which is already used in the [Cache-Control](https://www.rfc-editor.org/rfc/rfc9111.html#name-max-age), [Set-Cookie](https://datatracker.ietf.org/doc/html/rfc6265#autoid-13), and [Alt-Svc](https://datatracker.ietf.org/doc/html/rfc7838#section-3.1) header fields to denominate the lifetime of cookies and cache entries.
> Resumable Upload: Rename `expires` limit to `max-age`

- draft-ietf-httpbis-resumable-upload.md
Closes https://github.com/httpwg/http-extensions/issues/2874
In the past, the document used the term "target resource" to denote the resource that the initial request was sent to. This term is quite confusing, so since then we moved away from this term and used other descriptions. In this PR, the last two occurrences are removed.
In addition, it puts a brief mention of "upload resource" in the "Conventions and Definitions" section, so readers know early on what it is.
> Resumable Upload: Clear up definitions

- draft-ietf-httpbis-resumable-upload.md
This PR adds a problem type for servers to use when responding to requests that include inconsistent upload length values as explained in https://httpwg.org/http-extensions/draft-ietf-httpbis-resumable-upload.html#name-length.
With this PR, the draft defines a problem type for all (three) upload-specific error cases that are mentioned in the document. I think this might be useful for implementation.
Let me know if you think this isn't a good idea.
> Resumable Upload: Problem type for inconsistent length values

- draft-ietf-httpbis-resumable-upload.md
Because of the changes in https://github.com/httpwg/http-extensions/pull/3018 and https://github.com/httpwg/http-extensions/pull/3012
> Resumable Upload: Increase draft interop version to 7

- draft-ietf-httpbis-resumable-upload.md
First example had the Upload-Limit in the wrong 104 response.
In the second example I added a 104 to Upload-Complete: ?0 to make it clear that this interim response is sent here as well. No Upload-Offset interim though to show that it's optional.
> Make two examples clearer

- draft-ietf-httpbis-resumable-upload.md
In https://github.com/httpwg/http-extensions/pull/3027, the reference for structured fields was updated to RFC 9651, which demands that newly registered header fields define their structured fields. This PR adds the missing column.
See https://www.rfc-editor.org/rfc/rfc9651.html#iana and https://www.rfc-editor.org/rfc/rfc9651.html#name-changes-from-rfc-8941 for information about the new column.
> Define structured types for header fields

- draft-ietf-httpbis-resumable-upload.md
This PR is a proposal to slightly reword the introduction and make it more concise. Its mostly based on [Roy Fielding's feedback](https://mailarchive.ietf.org/arch/msg/httpbisa/m-iXTJQGdb8XpxGjZWxXGj6Siic/) but also incorporates a sentence about use cases for resumable uploads other than error recovery (that is, prioritizing network traffic as in https://github.com/httpwg/http-extensions/issues/2242, users pausing uploads, applications pausing uploads when device switches from WiFi to cellular).
Let me know what you think about this and whether it's an improvement or not!
Closes https://github.com/httpwg/http-extensions/issues/2242.
> Resumable Uploads: Rephrase introduction

- draft-ietf-httpbis-secondary-server-certs.md
> [Secondary-Server-Certs] Rename CERTIFICATE to SERVER_CERTIFICATE

- draft-ietf-httpbis-optimistic-upgrade.md
This changes makes it REQUIRED for proxy servers to close the connection after a failed HTTP/1.1 CONNECT ... with a legalistic escape hatch: this requirement only applies "when communicating with potentially vulnerable clients".
Presumably any client is potentially vulnerable unless you know something about it specifically.
See #2739
> [connect-tcp] Require close after CONNECT fails

- draft-ietf-httpbis-incremental.md
A few different things, happy to split them out.
1. Tweaks to language in the intro.
2. Security considerations heading can go (not enough stuff to justify subsections)
3. New security consideration (DoS through dribbling data in)
4. Register the header field in IANA considerations.
> Incremental tweaks

- draft-ietf-httpbis-incremental.md
Clarify that incremental delivery is only needed for the message body.
Closes #3054.
> can buffer the header / trailer sections

- draft-ietf-httpbis-safe-method-w-body.xml
Overall, this is very good, so these are very minor.
Feel free to cherry-pick or reject as you see fit.
> query: some editorial nits

- draft-ietf-httpbis-resumable-upload.md
In his [review](https://mailarchive.ietf.org/arch/msg/httpbisa/9dsNnPwl3j3TCuv1o7jL5Em5380/), Julian rightfully called out some incorrect uses of BCP14 keywords in the document.
This PR attempts to address these point by
- turning MAYs into "can"s where they just express a possibility,
- turning SHOULDs into MUSTs where appropriate,
- explaining SHOULD to aid reader in the decision process of whether to follow the advice or not.
Some of these changes are normative:
- Handling `OPTIONS *` is now optional
- Server must announce limits using `Upload-Limit`
- Clients must adhere to limits that they are aware of
- Server must prevent issues from concurrent requests, but are not required to achieve this by terminating previous requests. This gives server the ability to implement the approach …
> Resumable Upload: Correct usage of BCP14 keywords

- draft-ietf-httpbis-no-vary-search.md
Closes #3074, by making it clearer that the SHOULD requirement on server operators is in service of playing nicely with certain efficient cache implementation strategies.
> No-Vary-Search: rearrange cache efficiency considerations

- draft-ietf-httpbis-unencoded-digest.md
The spec is currently silent on the subject of parameters, and it seems reasonable to consistently make room for future extension by explicitly defining them as allowed but ignored. This has little practical impact, but hopefully ensures that implementers would treat `sha-256=:...:;options=plz` and `sha-256=:...:` as equivalent declarations.
> [Unencoded-Digest] Allow parameterized values.

- draft-ietf-httpbis-safe-method-w-body.xml
This changes the definition of 303 -> Location to identify the "stored query" for GET, representing _current_ results.
Interestingly enough, this is what the example showed already.
> QUERY: HTTPDIR/RF review - Redirection (closes #3119)
