draft-ietf-httpbis-http2-encryption.md

for encryption.
I had these in my local repo.  They weren't pushed, but I wanted to make sure that they are OK before merging them.

Editorial changes

---

draft-ietf-httpbis-alt-svc.xml

Use only one alternative service.

---

draft-ietf-httpbis-alt-svc.xml

Simple enough, as agreed previously.  Issue #72.

Wrong protocol is connection failure

---

draft-ietf-httpbis-alt-svc.xml

Even a pull request feels heavy-weight for this....

Remove extraneous comma

---

draft-ietf-httpbis-http2-encryption.md

I think that I caught everything in the first round of discussion.  There aren't any substantial changes here, but it's a PR so that others can confirm.

Julian's review

---

draft-ietf-httpbis-origin-frame.md

Some rather minor edits to the ORIGIN frame spec

ORIGIN Frame Minor edits

---

draft-ietf-httpbis-http2-encryption.md

Mike Bishop and Stefan Eissing need acknowledgment.

---

draft-ietf-httpbis-client-hints.md

Address feedback on client-hints-01 draft

---

draft-ietf-httpbis-encryption-encoding.md

Oops in the intro paragraph.

---

draft-ietf-httpbis-encryption-encoding.md

Adding OWS

---

draft-ietf-httpbis-encryption-encoding.md

Updates based on Magnus Westerlund's review.

Magnus review encryption

---

writeups/opp-sec.md

After much dancing to avoid sending you tens of "merging httpwg/master" commits....

Opp-Sec Shepherd Write-up

---

draft-ietf-httpbis-client-hints.md

See
https://lists.w3.org/Archives/Public/ietf-http-wg/2016OctDec/0146.html
@reschke ptal.

clarify Accept-CH

---

draft-ietf-httpbis-encryption-encoding.md

Remove Crypto-Key header field

---

draft-ietf-httpbis-rfc6265bis.md

we can't change the IPR clause from RFC 6265

incorrect IPR

---

draft-ietf-httpbis-encryption-encoding.md

header = 16 +4 + 1 +2 = 23
two records of 25 bytes = 50
sum is 73

incorrect content length in example

---

draft-ietf-httpbis-client-hints.md

Related discussions:
- https://lists.w3.org/Archives/Public/ietf-http-wg/2017JanMar/thread.html#msg143
- https://github.com/httpwg/http-extensions/issues/284

Incorporate feedback on httpbis-client-hints-03

---

draft-ietf-httpbis-client-hints.md

Closes https://github.com/httpwg/http-extensions/issues/308.

Editorial cleanup and improvements

---

writeups/opp-sec.md

For git tracking purposes, even though I'm uploading directly to Datatracker as well.

Updated Opp-Sec writeup

---

draft-ietf-httpbis-rfc6265bis.md

...about the changes in rfc6265

remove historic status text

---

draft-ietf-httpbis-rfc6265bis.md

make internal references dynamic

---

draft-ietf-httpbis-early-hints.md

... for your consideration; feel free to take, discard, or do whatever else you like :)

Editorial suggestions

---

draft-ietf-httpbis-rfc6265bis.md

(taken from 6265)
Note this requires kramdown-rfc2629 version 1.2.2 or newer  - please make sure to use this when generating submissions

augment downref to RFC 3490 with explanation (see #343)

---

draft-ietf-httpbis-origin-frame.md

...not just the wildcard ones.

The matching rules in 2818 all apply

---

.gitignore
Makefile
README.md
draft-ietf-httpbis-replay.md

Since our chairs have not seen the wisdom of separate repositories, I will acquiesce.

Add HTTP replay draft

---

draft-ietf-httpbis-origin-frame.md

Origin nits

---

draft-ietf-httpbis-replay.md

This explains how consistent handling of requests can be applied by a gateway.

Intermediaries need to be consistent too

---

draft-ietf-httpbis-rand-access-live.xml

Also added a new Security Consideration for JavaScript-based clients and servers.

Incorporated comments from MartinT and some of my own edits to draft-ietf-httpbis-rand-access-live

---

draft-ietf-httpbis-replay.md

These should all be editorial.

Changes in response to ekr's replay review

---

draft-ietf-httpbis-origin-frame.md

Explicitly scope to Origin Set

---

draft-ietf-httpbis-replay.md

John Mattsson pointed out that we didn't really discuss the risks of use of early data.  That's fair, but we don't need to.  This rewrites the abstract.

New abstract

---

draft-ietf-httpbis-replay.md

missing a word

---

draft-ietf-httpbis-expect-ct.md

Minor editorial fixes for Expect-CT

---

Makefile

Remove the repellent ribbon

---

draft-ietf-httpbis-bcp56bis.md
draft-ietf-httpbis-cache-digest.md
draft-ietf-httpbis-client-hints.md
draft-ietf-httpbis-early-hints.md
draft-ietf-httpbis-expect-ct.md
draft-ietf-httpbis-h2-websockets.md
draft-ietf-httpbis-header-structure.md
draft-ietf-httpbis-key.md
draft-ietf-httpbis-origin-frame.md
draft-ietf-httpbis-rfc6265bis.md

Uses {DATE} to let the date be auto-added at build time.

It's not 2017

---

draft-ietf-httpbis-replay.md

Thanks @davidben and @vasilvv for pushing on this.

Consistency fix

---

draft-ietf-httpbis-http2-secondary-certs.md

...which is how the RFC Editor likes it.

move acks to the end and make them unnumbered

---

draft-ietf-httpbis-rand-access-live.xml

This should match what was submitted for draft -03

Incorporated Darshak's editorial edits for (submitted) draft-ietf-httpbis-rand-access-live-03

---

draft-ietf-httpbis-header-structure.md

These were wreaking havoc with my syntax highlighting.

escape some more asterisks and underscores

---

draft-ietf-httpbis-header-structure.md

add padding to binary value in example

---

draft-ietf-httpbis-cache-digest.md

@kazuho As discussed, here's a PR for changing the draft authorship.
Thanks!

Change Cache Digests authorship

---

draft-ietf-httpbis-h2-websockets.md

h2-ws: artwork width

---

draft-ietf-httpbis-replay.md

Just editorial suggestions here, but all good ones.

ekr's review of replay

---

draft-ietf-httpbis-replay.md

This will conflict with the changes ekr suggested, but I integrated them, so merging shouldn't lose the important changes.

Spencer's q

---

draft-ietf-httpbis-replay.md

Mostly the text got shorter, which is a nice bonus.

Ben C review comments

---

draft-ietf-httpbis-cache-digest.md

Closes https://github.com/httpwg/http-extensions/issues/516

Remove etag and validators

---

draft-ietf-httpbis-header-structure.md

[SH] change a comma and a parenthetical

---

draft-ietf-httpbis-header-structure.md

Tweak some examples to make them a bit more valid

[SH] tweak examples

---

draft-ietf-httpbis-header-structure.md

[SH] make "parse a boolean" consume the T/F char

---

draft-ietf-httpbis-rfc6265bis.md

Closes https://github.com/httpwg/http-extensions/issues/199
@johnwilander, mind taking a look?

RFC6265bis: Include 'host-only-flag' when calculating uniqueness.

---

draft-ietf-httpbis-cdn-loop.md
draft-ietf-httpbis-client-hints.md

Suggested elaboration / re-focusing in the introduction to clarify how CH fits into things.

CH suggestions

---

README.md

Remove URL redirection

---

draft-ietf-httpbis-http2-secondary-certs.md

Fixes #660, but I'd prefer a better recommendation here than "educate your customers."

Persistence of service text

---

draft-ietf-httpbis-proxy-status.md

Proxy-Status: remove error restriction in http_response_status.

---

README.md
draft-ietf-httpbis-http2-tls13.md

Per @mcmanus, I've added a dummy artwork block to work around https://github.com/martinthomson/i-d-template/issues/188

Add draft-ietf-httpbis-http2-tls13.md

---

draft-ietf-httpbis-proxy-status.md

Proxy-Status: add Proxy Internal Response.

---

draft-ietf-httpbis-digest-headers.md

Fix: #822. 
Adds the digest-headers draft to the repository.
The original repository, with the issues to be migrated, is here:
- https://github.com/ioggstream/draft-polli-resource-digests-http

Add digest headers draft.

---

draft-ietf-httpbis-digest-headers.md

Fix: #827. typo in reference: FIPS-180 -> FIPS180

---

draft-ietf-httpbis-digest-headers.md

Fixes unused references.    
- Removed reference to FIPS180-4 and opened issue #832
- Removed unneeded references
- Uses required references.

Fix unused references

---

draft-ietf-httpbis-digest-headers.md

Fix: #834. Add -latest to docname.

---

draft-ietf-httpbis-digest-headers.md

removes citations from abstract.

Fix: #836. Remove citations from abstracts.

---

draft-ietf-httpbis-digest-headers.md

see https://tools.ietf.org/html/rfc7322#section-3.5

use standard form for referring to RFCs

---

draft-ietf-httpbis-header-structure.md

Change parameterized lists to have primary items

---

draft-ietf-httpbis-header-structure.md

Roughing in collapse of ParamList into List

---

draft-ietf-httpbis-proxy-status.md

Proxy-Status: merge tls_unexpected_peer_{certificate,identity}.

---

draft-ietf-httpbis-http2-tls13.md

Per
https://github.com/martinthomson/i-d-template/pull/189#issuecomment-495170877,
the fix should be picked up automatically, but local copies will need to be
updated. cd lib && git pull appears to do the trick.

Remove workaround for addstyle.sed bug.

---

draft-ietf-httpbis-client-hints.md

Closes #700
@mnot - can you take a look?

[Client Hints] Replace ABNF with Structured Headers

---

draft-ietf-httpbis-client-hints.md

Closes #730
@mnot - It's not very descriptive, and seems like each CH feature will have to specify its own Variants model, but mentioning it seems like a good idea. Also, I'm not sure how to setup the related links in a nicer way.

Replace Key with Variants

---

draft-ietf-httpbis-client-hints.md

Closes #761 
@dbaron - can you take a look and see if that clarifies things?

Clarify defined headers are response headers

---

draft-ietf-httpbis-digest-headers.md

Fixes the digest values b/w request and response, which were swapped.
#881

Fix #881: digest for br-compressed representations

---

draft-ietf-httpbis-digest-headers.md

fixing typo

---

README.md

Align README with BCP56bis title. See #595

---

draft-ietf-httpbis-digest-headers.md

Adds id-sha-* algorithm examples throughout the document.

Fix: #880. Add id-sha-* algorithm examples.

---

draft-ietf-httpbis-digest-headers.md

Align the I-D title with the .md file name suggested by @mnot before the adoption.

Fix: #886. Align title with document name.

---

draft-ietf-httpbis-header-structure.md

Allow dictionary members to have parameters.

---

draft-ietf-httpbis-header-structure.md

Clamp floats

---

draft-ietf-httpbis-header-structure.md

[SH] add reference for UTF-8

---

draft-ietf-httpbis-header-structure.md

[SH] say 1=true, 0=false

---

draft-ietf-httpbis-digest-headers.md

Fix: #825. Add post -00 sections.

---

draft-ietf-httpbis-digest-headers.md

- removes trailing spaces
- links rfcs

Fixing typos

---

draft-ietf-httpbis-http2-tls13.md

This addresses feedback from the list:
https://lists.w3.org/Archives/Public/ietf-http-wg/2019JulSep/0266.html
https://lists.w3.org/Archives/Public/ietf-http-wg/2019JulSep/0271.html
@martinthomson @MikeBishop, does this look good to you?

http2-tls13: Address feedback from list

---

draft-ietf-httpbis-digest-headers.md

Fix: #927. Unnumbered section should be the lasts

---

draft-ietf-httpbis-digest-headers.md

Adds an example with PUT + 204 No Content.
Response contains a Digest computed on the selected representation.
Related to #853
Fixes #925

Fix: #925. Example with PUT+204.

---

draft-ietf-httpbis-digest-headers.md

Fix: #934. Reformat artworks.

---

draft-ietf-httpbis-digest-headers.md

Fix: #938. Add code samples.

---

draft-ietf-httpbis-digest-headers.md

Try to set country

---

draft-ietf-httpbis-digest-headers.md

Updates the IANA digest-algorithms table with the reference to CRC32C

Update CRC32C value in iana table. Related to: #828.

---

draft-ietf-httpbis-digest-headers.md

Ioggstream typos 1

---

draft-ietf-httpbis-proxy-status.md

Proxy-Status: replace last occurrence of "details".

---

draft-ietf-httpbis-digest-headers.md

Fix typo: Request-URI.

---

draft-ietf-httpbis-header-structure.md

Allow parameters on Items and Inner Lists

---

.circleci/config.yml

The caching in the old setup was broken.  Mike fixed it for me in QUIC and I ported that along.  It should help quite a bit with build times when things get busy.

Update circle config for better caching

---

draft-ietf-httpbis-digest-headers.md

My intention of this PR was to fix #868 (relationship to SRI) and #872 (use case).
Having reviewed the I-D, IMO it already explained a few general use cases, so I did some word smithing to make them jump out some more. We can expand on these further if needs be.
I wanted to break out the SRI stuff, but ran out of time today to fully complete that so the PR is WIP.
Finally, the usage in signatures section seemed to benefit from some tidy up too. I don't think we've fully completed the ask on #851 and I'm inclined to leave it that way for the time being.

digest: editorial sweep and address use cases and SRI

---

draft-ietf-httpbis-digest-headers.md

Clarifies the relations b/w Digest,  PATCH and POST:
- PATCH and POST does not convey partial representations;
- they instead specify actions on resources
In requests:
- Digest should refer to the representation-data of the action
In responses:
- if the enclosed representation refers to the status of the action, then it's complete and Digest is computed on it;
- if the enclosed representation referers to another resource (eg. via content-location), Digest is computed on the selected representation of that resource;
- the above is true even in case of an empty payload body.

Fix #853. Use when acting on resources

---

draft-ietf-httpbis-digest-headers.md

Splits sentence over multiple lines.

Split sentences on multiple lines.

---

draft-ietf-httpbis-digest-headers.md

Add changelog for acting on resources and SRI.

Add changelog for acting on resources and SRI.

---

draft-ietf-httpbis-header-structure.md

fix inner-list in ListListParam example

---

draft-ietf-httpbis-client-hints.md

I want to republish the CH draft as it expired, and the change logs didn't include a bunch of the recent changes.
@igrigorik @mnot - Can you take a look?

[Client Hints] Cleanups for publishing

---

draft-ietf-httpbis-client-hints.md

Closes #962 
@martinthomson - Took a first stab at describing the cost of hints and the fact that servers should not overuse them. Let me know what you think.
/cc @igrigorik

Describe the bytesize cost of hints

---

draft-ietf-httpbis-header-structure.md

I'm really not sure what happened there, but don't have time to investigate.
I suspect GitHub didn't actually merge.

Let's try this again.

---

draft-ietf-httpbis-client-hints.md

A first pass at resolving #786 
@igrigorik & @martinthomson - Can you take a look and see if this properly sums up our Monday conversations?

Detail dimensions of information exposure

---

draft-ietf-httpbis-client-hints.md

Closes #957 
@igrigorik - can you review?

Clear CH persistence when session cookies are cleared

---

draft-ietf-httpbis-header-structure.md

Change value of omitted parameter value to True

---

draft-ietf-httpbis-header-structure.md

... and allow token to start with "*".
Fixes #991.

Change byte sequence delimiters from "*" to ":"

---

draft-ietf-httpbis-header-structure.md

change parsing of bare item to handle * and : correctly

---

draft-ietf-httpbis-priority.md

Based on the up-to-date version on https://github.com/kazuho/draft-kazuho-httpbis-priority/.

add priority draft

---

draft-ietf-httpbis-header-structure.md

Float -> Decimal

---

draft-ietf-httpbis-header-structure.md

Overwrite duplicate dictionary values

---

draft-ietf-httpbis-header-structure.md

Encourage end-to-end grease by applications

---

SUBMITTING.md

Update `SUBMITTING.md` to note email address requirements.

---

draft-ietf-httpbis-client-hints.md

This PR addresses Client Hints [LC feedback](https://lists.w3.org/Archives/Public/ietf-http-wg/2020JanMar/0141.html) from @reschke.

[client hints] LC feedback from @reschke

---

draft-ietf-httpbis-digest-headers.md

- Adds further HTTP semantics impacts on the representation.
- Add security considerations for content-location.

Fix: #952. Content-Location impacts on digest

---

draft-ietf-httpbis-priority.md

Address some build warnings and fix typos.

fix some priority doc nits

---

draft-ietf-httpbis-priority.md

priority: remove mention of CDN-loop

---

draft-ietf-httpbis-header-structure.md

Omitted True dictionary value can have parameters

---

draft-ietf-httpbis-priority.md

Cherry-pick editorial improvements from #1041

---

draft-ietf-httpbis-client-hints.md

[client-hints] Editorial feedback

---

draft-ietf-httpbis-priority.md

We made some design changes and closed issues, lets now capture that in the changelog.

changelog for priority-00

---

draft-ietf-httpbis-digest-headers.md

Moves header definitions on top level

Promote header field. See #1103.

---

draft-ietf-httpbis-digest-headers.md

Moves deprecated algorithms in the iana table.

Refactor deprecated algorithms. See #1103.

---

draft-ietf-httpbis-digest-headers.md

Add headings for examples

---

draft-ietf-httpbis-priority.md

...according to RFC Style Guide.

priority: fix external section reference format

---

draft-ietf-httpbis-digest-headers.md

Moves Want-Digest after Digest.﻿

Shift Want-Digest down. See #1103.

---

draft-ietf-httpbis-digest-headers.md

Merges encoding examples.
See #1103

Merge encoding examples. See #1103.

---

draft-ietf-httpbis-digest-headers.md

moves the computation part under Digest﻿

Move digest computation under Digest. See #1103

---

draft-ietf-httpbis-digest-headers.md

Introduces properly Representation Digest, which is the core concept of the spec.
The original draft name was in fact `Representation Digest`.
See #1103

Introduce resource digest #1103

---

draft-ietf-httpbis-digest-headers.md

Adds changelog to Digest Headers.
Related to: #1103

Add changelog to digest-headers.

---

draft-ietf-httpbis-digest-headers.md

Fixes various typos along the document.

Digest Headers: fix typos

---

draft-ietf-httpbis-client-hints.md

@reschke - here's the nicer list style you ordered :)

Fix list style based on comment from @reschke

---

draft-ietf-httpbis-client-hints.md

Non substantive change to improve the list's style, after feedback on https://github.com/httpwg/http-extensions/pull/1080#discussion_r390275413

[Client Hints] Remove nested list

---

draft-ietf-httpbis-http2-secondary-certs.md

Fixes #870.  I believe that @davidben's comment on that issue is already covered by the following section on Denial of Service.

Client privacy

---

draft-ietf-httpbis-digest-headers.md

adds an example without content coding

Integrate an example without content coding.

---

draft-ietf-httpbis-client-hints.md

A set of changes following comments as part of the AD review process.

[client hints] AD review comments

---

draft-ietf-httpbis-digest-headers.md

Deprecates SHA-1 as it's now vulnerable to collisions.
Fixes: #1020

Fix: #1020. Deprecate sha-1

---

draft-ietf-httpbis-digest-headers.md

mentions mid-stream trailers in the FAQ. They cannot be treated easily in this spec
as they are an hypothesis for now. Future digest-algos may consider them.

Mention mid-stream trailers in the FAQ.

---

draft-ietf-httpbis-digest-headers.md

- adds an example of a request with no payload body (eg. HEAD)
- mention an use-case in the Signature section.
Fixes: #1143

Fix: #1143. Example of an empty payload body.

---

draft-ietf-httpbis-digest-headers.md

References I-D.httpbis-semantics using an inline referece to {{SEMANTICS}}.
This will ease the transition once SEMANTICS is updated to RFC.

Create an inline reference to semantics.

---

draft-ietf-httpbis-header-structure.md

Correct indentation in ser-dictionary

---

draft-ietf-httpbis-digest-headers.md

(it only exists in Accept-Encoding)

"identity" is not a valid field value for "Content-Encoding"

---

draft-ietf-httpbis-priority.md

Fixes #1217 and #1218.
I've left Security Consideration as TBD, I'll fill that out in a separate PR.

move Fairness and client scheduling to top level

---

draft-ietf-httpbis-digest-headers.md

digest-headers: fix HTTP Semantics references

---

draft-ietf-httpbis-proxy-status.md

Collapse TLS errors down to two.

---

draft-ietf-httpbis-proxy-status.md

Fix typos.

---

draft-ietf-httpbis-digest-headers.md

digest-headers: Fix typos, add changelog.

---

draft-ietf-httpbis-digest-headers.md

- editorial fix of digest-algorithms

Align missing digest-algorithm parts. See #1211

---

draft-ietf-httpbis-priority.md

bespoke is uncommon

---

draft-ietf-httpbis-digest-headers.md

Describes how to achieve algorithm agility:
- add Status to IANA table;
- use Want-Digest to negotiate newer algos
- use multiple digest values while transitioning to new algos (see https://tools.ietf.org/html/rfc7696#section-2.3 but I didn't cite it as I don't think it is worth unless we want to add MANDATORY algorithms)
I didn't merge this section with IANA Considerations because of [Keep IANA Considerations for IANA]( https://tools.ietf.org/html/rfc8126#section-1.1)

Achieving algorithm agility. See #1250

---

draft-ietf-httpbis-digest-headers.md

- obsoletes digest parameters
See #850

Fix: #850. Obsolete parameters.

---

draft-ietf-httpbis-digest-headers.md

Add changelog since -03

---

draft-ietf-httpbis-digest-headers.md

- minor editorial improvements

digest: minor editorial typos

---

draft-ietf-httpbis-digest-headers.md

Validate HTTP message examples in Digest

---

draft-ietf-httpbis-message-signatures.md

Generalize the HTTP messaging protocol.

Generalize HTTP protocol

---

draft-ietf-httpbis-message-signatures.md

- separates MESSAGING and SEMANTICS concepts (Eg. fields)

Method is defined in semantics. See #1214.

---

draft-ietf-httpbis-message-signatures.md

removes trailing whitespaces :D

remove trailing whitespaces

---

draft-ietf-httpbis-digest-headers.md

Provides non-normative feedback on duplicate digest-algorithms

Fix: 1221. Non-normative hints for duplicate digest-algorithms.

---

draft-ietf-httpbis-digest-headers.md

also changes "payload body" to "payload data"

digest-headers: ref http core -13

---

draft-ietf-httpbis-digest-headers.md

Fixes field ordering reference

Fix #1342: refs to field ordering in semantics

---

draft-ietf-httpbis-digest-headers.md

Set author country

---

draft-ietf-httpbis-digest-headers.md

This ended up being more changes than I first intended but I think most of them are uncontroversial and simply improve consistency through the document.

digest: end of 2020 editorial pass

---

draft-ietf-httpbis-digest-headers.md

Editorial changes by @LPardue - rebased.

Ioggstream digest end of 2020 editorial pt2

---

draft-ietf-httpbis-digest-headers.md

- adds missing headers in examples

Fix: #1356. Missing headers in examples

---

draft-ietf-httpbis-priority.md

Remove resolved priority fairness TODO

---

draft-ietf-httpbis-priority.md

parameter registration process

---

draft-ietf-httpbis-digest-headers.md

adds content-location, content-length 
Fix: #1374, #1358, #1365

Fix: #1365. Add missing headers

---

draft-ietf-httpbis-digest-headers.md

Fix: #1395. Obsolete RFC3230.

---

draft-ietf-httpbis-digest-headers.md

includes security considerations from #852

Fix: #852. Mention resource consumption.

---

sf.json

I think this was our decided path forward, I still had some garbage in my local work copy see https://github.com/httpwg/http-extensions/pull/1344/files#r546142029

add priority field

---

draft-ietf-httpbis-proxy-status.md

Fix markdown.

---

draft-ietf-httpbis-digest-headers.md

Use "content" instead of "payload data".

Fix: #1408. Use semantics-14.

---

draft-ietf-httpbis-digest-headers.md

digest: fix SRI section ref

---

draft-ietf-httpbis-bcp56bis.md

...and fix one more weird link.

bcp56bis: make field registration link more specific

---

draft-ietf-httpbis-bcp56bis.md

...and fix one more weird section link.

bcp56bis: make ref to conditional requests more specific

---

draft-ietf-httpbis-safe-method-w-body.xml

- content-type / media type
- header / header field

Minor editorial fixes

---

draft-ietf-httpbis-rfc6265bis.md

rfc6265bis: uppercase "sections"

---

draft-ietf-httpbis-digest-headers.md

Fix: #1489. FAQ to be removed.

---

draft-ietf-httpbis-digest-headers.md

adds section Changes from 3230

Fix: #1484. Add section Changes from 3230

---

draft-ietf-httpbis-rfc6265bis.md

Fixes #1301 - Consistently use "header field"

---

draft-ietf-httpbis-message-signatures.md

Fix a small typo in the document.

Fix small typo

---

draft-ietf-httpbis-message-signatures.md

Minor editorial cleanup and release of signatures draft -05.

Release Signatures -05

---

draft-ietf-httpbis-client-cert-field.md

This was languishing in a PR within my repo, but since we've merged the actual draft, we can promote this to a PR in the main repo as well.
(Yes, I'll rename the tag if we merge this as-is.)

First pass for header/field terminology

---

draft-ietf-httpbis-priority.md

As suggested by https://github.com/httpwg/http-extensions/issues/1429.

Add a section for http prioritization in transport retransmission

---

draft-ietf-httpbis-priority.md

State the H2 priority signals explicitly

---

draft-ietf-httpbis-safe-method-w-body.xml

This minor nit was the only thing that jumped out at me during a read-through before the interim.

Extra word in SEARCH

---

draft-ietf-httpbis-priority.md

This PR talks about the server-side recommendation discussed in https://github.com/httpwg/http-extensions/pull/1544#discussion_r652288138.

suggest intermediaries might avoid strict prioiritization

---

draft-ietf-httpbis-priority.md

priorities apply to HTTP and may be used by extensions

---

draft-ietf-httpbis-priority.md

priorities: CONNECT can be prioritized too

---

draft-ietf-httpbis-digest-headers.md

Fix: #1377. Reboot digest-algorithm values registry.

---

draft-ietf-httpbis-rfc6265bis.md

Fix minor typo

---

draft-ietf-httpbis-rfc6265bis.md

RFC 6565bis: Add length limits to storage model algorithm

---

draft-ietf-httpbis-priority.md

We never use sf-token but do use sf-integer

fix wrong sf- import

---

draft-ietf-httpbis-priority.md

We're keeing reprioritization, no need for this TBD any longer.

remove a stale TBD

---

draft-ietf-httpbis-expect-ct.md

See, not that hard.
Closes #1572.

Fix trailing whitespace

---

draft-ietf-httpbis-message-signatures.md

Minor editorial cleanups, including:
- added client cert example
- updated multiple signature example
- prepare for next revision

Release Signatures 06

---

draft-ietf-httpbis-rfc7838bis.md

Discussion venue note

---

draft-ietf-httpbis-proxy-status.md

... and rewrite trailer bits for clarity

Add a trailer merging algorithm

---

draft-ietf-httpbis-digest-headers.md

- cleanup POST/PATCH section with feedback from @mnot and @reschke

Digest: POST/PATCH cleanup 

---

draft-ietf-httpbis-digest-headers.md

- remove SRI Section #1478. @LPardue will publish that under a blog post.
- add changelog -05

Fix: #1478. Remove SRI section. Add changelog.

---

draft-ietf-httpbis-digest-headers.md

Fixes #1661.
Preview at: https://httpwg.org/http-extensions/lucas/rationalise-want-fields/draft-ietf-httpbis-digest-headers.html

condense digest Want field definitions

---

draft-ietf-httpbis-digest-headers.md

- renames the document to `Digest Fields`
- improve consistency in terminology

Fix: #1632. Consistent use of Digest fields.

---

draft-ietf-httpbis-rfc6265bis.md

Fixes #1627 - Remove outdated comments related to Secure attribute

---

draft-ietf-httpbis-digest-headers.md

fixes #1483 
The MD diff is rendered pretty badly, see https://tools.ietf.org/rfcdiff?url1=https://httpwg.github.io/http-extensions/draft-ietf-httpbis-digest-headers.txt&url2=https://httpwg.github.io/http-extensions/move-digest-example-to-appendix/draft-ietf-httpbis-digest-headers.txt for a better view

move digest examples to appendix

---

draft-ietf-httpbis-rfc7838bis.md

Cite HTTP for 421

---

draft-ietf-httpbis-digest-headers.md

Thanks to Julian Reschke et al.

---

draft-ietf-httpbis-priority.md

Subsumes #1688.
@ianswett @LPardue Please check if the changes cover the points that should be covered.

Editorial follow-up from 1601 (alternative to 1688)

---

draft-ietf-httpbis-priority.md

expand why and when intermediaries might want to use a frame

---

draft-ietf-httpbis-priority.md

Fixes #1765.
Minimal change to put focus on what endpoint do with this.

tweak NO_RFC7540 text

---

draft-ietf-httpbis-priority.md

Add a mising "that"

---

draft-ietf-httpbis-digest-headers.md

- strip out id-* algorithms from this spec
- id- are complex to address in this document
- they will be better addressed in https://github.com/ioggstream/draft-polli-id-digest-algorithms

Fix: #855. Remove id-sha-*.

---

draft-ietf-httpbis-priority.md

Not a complete solution, but hopefully helpful.  More to come for those who are less cautious than
I.

Be clearer about handling of h2 priority

---

draft-ietf-httpbis-priority.md

explain more about the client SHOULDs wrt H2 setting

---

draft-ietf-httpbis-binary-message.md
draft-ietf-httpbis-rfc6265bis.md

I'm pleased to see that adding the file is all that is necessary.
I didn't retain the history of the file; this is a simple copy.  It's a bit of work to figure out
how to do that.

Add binary messages

---

draft-ietf-httpbis-priority.md

I complained about this text in my last review, but was told that it was very important.
Improvements here are still possible.  Mostly by cutting text.

Less h2 bashing

---

draft-ietf-httpbis-message-signatures.md

Adds security and privacy considerations and applies various cleanups including those suggested by early security review

Security and Privacy Considerations for Signatures

---

draft-ietf-httpbis-priority.md

- articles for control stream
- parenthesise reference

Sec directorate review feedback

---

draft-ietf-httpbis-priority.md

In the Genart review of this document, it was requested to provided citations of such experiments. These two are the best examples I can think of, which came up during the motivation to form a priorities design team and take on the work.
@rmarx does this reference to your paper look ok?

cite experiments of simpler priority schemes

---

draft-ietf-httpbis-priority.md

Integrate RFC 7540 replacement with deprecation notage

---

draft-ietf-httpbis-priority.md

Takign some of the suggestion on #1802﻿

uncontroversial nits from Bob

---

draft-ietf-httpbis-priority.md

Reword sentence that cites CACHING

---

draft-ietf-httpbis-priority.md

Be specific about the incremental streams guidance we refer to

---

draft-ietf-httpbis-priority.md

As discussed in https://github.com/httpwg/http-extensions/issues/1819#issuecomment-987199413 and https://github.com/httpwg/http-extensions/issues/1820#issuecomment-987196961, describe fairness and how that relates to priorities.
Closes #1819, closes #1820.

describe fairness and how that relates to priorities

---

draft-ietf-httpbis-priority.md

Small editorial nit in relation to #1820.

be clear what "precedence" means

---

draft-ietf-httpbis-priority.md

closes #1794
This is a derivative of my suggestion on https://github.com/httpwg/http-extensions/issues/1794#issuecomment-974212727

Better articulate server competition challenges

---

draft-ietf-httpbis-h3-websockets.md

Recommend 501 for unknown protocols

---

draft-ietf-httpbis-digest-headers.md

* Remove stale reference to Want-Digest change that is no longer in this doc
* Link Structured Fields RFC

FAQ tidyup

---

draft-ietf-httpbis-digest-headers.md

Fix: #1839. Remove cleartext references.

Fix: #1839. Remove cleartext references.

---

draft-ietf-httpbis-digest-headers.md

Fix: #1840. Add syntactic compatibility.

Fix: #1840. Add syntactic compatibility.

---

draft-ietf-httpbis-digest-headers.md

Fixes #1838 
Spotted another mention of accidental while I was at it, so changed that too.

Corruption of data is not always only accidental

---

draft-ietf-httpbis-digest-headers.md

Fix: #1844. Consistent use of "checksum".

Fix: #1844. Consistent use of checksum.

---

draft-ietf-httpbis-digest-headers.md

Fix: #1841.
-  Reference Algorithm substitution.
- details on algorithm agility

Fix: #1841. Reference Algorithm substitution.

---

draft-ietf-httpbis-digest-headers.md

Fixes #1833 
This seems like a better flow to me.
This is a bit hard to review. I'd check the editor's copy built from the branch.

Merge representation digest definition with Digest header one

---

draft-ietf-httpbis-priority.md

Section 7.3 includes a nice qualifier sentence, so let's pull it into 7.2 too.

Only clients send H2 frames

---

draft-ietf-httpbis-h3-websockets.md

As per feedback from Francesca Palombini

Add "status", "change controller" and "contact" to IANA registration

---

draft-ietf-httpbis-client-cert-field.md

shorten title of draft-ietf-httpbis-client-cert-field #1553

---

draft-ietf-httpbis-client-cert-field.md

Attempt to cover client-cert and caching interactions per mnot's guidance in issue #1736

client-cert caching interactions

---

draft-ietf-httpbis-client-cert-field.md

fill out client-cert's IANA Considerations with HTTP field name registrations to fix #1520

fill out client-cert's IANA section

---

draft-ietf-httpbis-message-signatures.md

- update canonicalization rules, remove weird headers from examples
- changed dictionaries and messages.
- updated crypto primative functions
- regenerate examples

Update Examples, Publish -08

---

draft-ietf-httpbis-binary-message.md

Remove duplicate venue info; fix presentation of IANA considerations; remove stub appendix.

Some cleanup of binary messages

---

draft-ietf-httpbis-binary-message.md

These aren't THAT surprising, but it is worth being explicit.

Add a section on differences with protocols

---

draft-ietf-httpbis-binary-message.md

I found this a little awkward when I re-reviewed it.

Tweak the description of informational responses

---

draft-ietf-httpbis-binary-message.md

Update message/* usage

---

draft-ietf-httpbis-binary-message.md

Connect is nonsense

---

draft-ietf-httpbis-message-signatures.md

Update query parameter generation in examples, closes #1901
﻿

Update signature examples for query

---

draft-ietf-httpbis-message-signatures.md

Includes several document cleanups for signatures, to publish as -09
Closes #1921
closes #1907
closes #1867
closes #1951

Signature Document Cleanups

---

draft-ietf-httpbis-digest-headers.md

Fix: #1837. Mention collisions.

Fix: #1837. Mention collisions.

---

draft-ietf-httpbis-digest-headers.md

- improves description of example with c-digest and r-digest
Fix: #1843

Fix: #1843. Improve example description.

---

draft-ietf-httpbis-digest-headers.md

- move r-digest related section to §2

Fix: #1967. All of representation digest in section 2.

---

draft-ietf-httpbis-digest-headers.md

- simplifies IANA field registration section
- obsolete Digest

Simplify IANA registration section.

---

draft-ietf-httpbis-message-signatures.md

Includes some new text and several small cleanups.
Closes #1192
Closes #1193
﻿

Release signature-09

---

draft-ietf-httpbis-binary-message.md

The diagram resulted in a few double-takes that might be helped by a little bit of a note pointing
this out.
Closes #1947.

Information status is response only

---

draft-ietf-httpbis-binary-message.md

Pseudo-fields aren't allowed in trailers

---

draft-ietf-httpbis-binary-message.md

Acknowledge David S

---

draft-ietf-httpbis-message-signatures.md

Fix references to "token endpoint authorization method"

---

draft-ietf-httpbis-message-signatures.md

Fix component mismatch in examples

---

draft-ietf-httpbis-message-signatures.md

Replace "input identifier" with "component identifier"

---

draft-ietf-httpbis-message-signatures.md

Fix minor grammar issues

---

draft-ietf-httpbis-message-signatures.md

Update terminology introducing derived component values

---

draft-ietf-httpbis-message-signatures.md

Component Identifier/Name terminology and usage

---

draft-ietf-httpbis-priority.md

IANA considerations style fixups

---

draft-ietf-httpbis-priority.md

streams carry requests, not methods

---

draft-ietf-httpbis-priority.md

Frame defs and examples are art

---

draft-ietf-httpbis-h3-websockets.md

Auth48: Websockets => WebSockets

---

draft-ietf-httpbis-priority.md

Closes #2006
A parameter by any name would be sweet

Tweak IANA stuff

---

draft-ietf-httpbis-priority.md

Try to avoid saying payload where it is not needed

---

draft-ietf-httpbis-rfc6265bis.md

Editorial: be consistent when aborting steps

---

draft-ietf-httpbis-priority.md

I'm not sure if 1c10233 is applicable.

auth48 tiny editorial nits

---

draft-ietf-httpbis-priority.md

Intermediary signal processing/production, again

---

draft-ietf-httpbis-h3-websockets.md

Auth48: Add "extended connect" keyword

---

draft-ietf-httpbis-digest-headers.md

Fix: #2042. Add changelog.

---

draft-ietf-httpbis-digest-headers.md

A comment was raised during the previous WGLC that this order would be more natural. We held off from applying it early to avoid large churn.
On it's own it might look like a lot of change but it is mostly just a swap. Only some gentle editorial tweaking was needed.

Swap Content and Repr digest presentation order

---

draft-ietf-httpbis-message-signatures.md

Switched to generic request-response binding

---

Makefile

This includes a change to the name of the binary, plus a tweak to work around for https://github.com/mnot/http_sfv/issues/9

Fix http-validate use/install

---

draft-ietf-httpbis-digest-headers.md

Fix #2100: unquote representation data

---

draft-ietf-httpbis-digest-headers.md

Clarify Integrity preference field meaning in responses

---

draft-ietf-httpbis-binary-message.md

Fix nits in binary-messages

---

draft-ietf-httpbis-binary-message.md

Just a little more explanation.
Closes #2119.  And #8174.

How informational and final status codes work

---

draft-ietf-httpbis-client-cert-field.md

add a note about cert retention on TLS session resumption (to fix #1992)

add a note about cert retention on TLS session resumption (to fix #1992)

---

draft-ietf-httpbis-digest-headers.md

The phrase "uncertainty of doubt" jumped out in this text as probably not being what was intended.
I fixed that and made just a few tweaks to adjacent text.

Editorial tweaks of appx D

---

draft-ietf-httpbis-binary-message.md

Arguably a technical change, though as it is in a picture, so I want to highlight it.
This is on top of #2127, so just look at 5468983321b104de62b1aae8df8963ad1abd5fa9 if you want to see the "technical" change.

Remove content ellipsis

---

draft-ietf-httpbis-digest-headers.md

Fix: 2181. Example chunked text.

---

draft-ietf-httpbis-digest-headers.md

Fix: #2168. add normative RFC8792.

---

draft-ietf-httpbis-rfc6265bis.md

It feels like we've missed a bunch of those recently, so I added the remaining changes to the changelog. I'm not sure I got the versioning right, though.

[6265bis] Changelog Updates

---

draft-ietf-httpbis-binary-message.md

This should make the whole thing less janky.

Tweaks to list intro and item 2

---

draft-ietf-httpbis-binary-message.md

From comments from Murray and Alexey.

Fix binary message registration

---

draft-ietf-httpbis-digest-headers.md

Fix: #2182. 4xx and 5xx are both valid responses.

---

draft-ietf-httpbis-digest-headers.md

digests: improve document structure section

---

draft-ietf-httpbis-message-signatures.md

- fix IANA registry text
- clean up signature parameters language

Clean up and release Signature draft

---

draft-ietf-httpbis-message-signatures.md

Add ECDSA over P-384

---

draft-ietf-httpbis-retrofit.md

Introduce and use the Date type

---

draft-ietf-httpbis-message-signatures.md

- set justin to editor
- re-ordered security considerations

signatures 12

---

draft-ietf-httpbis-resumable-upload.md

duplicate anchor for "Feature Detection"

resumable-uploads: fix XML breakage

---

draft-ietf-httpbis-client-cert-field.md

try to align better with the style guide on structured fields usage
for #2285

align better with the style guide wrt structured fields (for #2285)

---

draft-ietf-httpbis-message-signatures.md

Fix formatting issues in example

---

draft-ietf-httpbis-message-signatures.md

make 8792 informative

---

draft-ietf-httpbis-message-signatures.md

collects a few minor changes that missed -15 (including the changelog)

missed a few bits

---

draft-ietf-httpbis-origin-h3.md

Fixes #2273 in the manner discussed in London: Admitting it exists, but we don't care.

No flags, no worries

---

draft-ietf-httpbis-sfbis.md

Move ABNF to an appendix

---

draft-ietf-httpbis-alias-proxy-status.md

Remove trailing dot in CNAME examples

---

draft-ietf-httpbis-alias-proxy-status.md

Clarify alias/canonical name usage

---

draft-ietf-httpbis-alias-proxy-status.md

Formalize percent encoding for names in list

---

draft-ietf-httpbis-message-signatures.md

Update multi-signature examples

---

draft-ietf-httpbis-message-signatures.md

update language on structured fields

---

draft-ietf-httpbis-message-signatures.md

Update the semantics of parameters in Accept-Signature to be more fully defined and explicit.
Closes #2365

Update processing of parameters in Accept-Signature

---

draft-ietf-httpbis-message-signatures.md

Thanks to @cabo for the magic syntax.

update reference stye for HTTP/1.1

---

draft-ietf-httpbis-resumable-upload.md

Closes https://github.com/httpwg/http-extensions/issues/2349

Remove tus from Resumable Upload draft

---

draft-ietf-httpbis-digest-headers.md

Wrap all cases where repr-digest was 2 characters over

---

draft-ietf-httpbis-digest-headers.md

use hex-encoding for brotli examples

---

draft-ietf-httpbis-message-signatures.md

- Add reference for obs-fold, closes #2411 
- add note about transforms, closes #2410

Add reference and discussion of obs-fold and whitespace and other transformations

---

draft-ietf-httpbis-client-cert-field.md

Updates from Genart Last Call review https://lists.w3.org/Archives/Public/ietf-http-wg/2023JanMar/0138.html

client-cert: genart review updates

---

draft-ietf-httpbis-alias-proxy-status.md

Mention the empty string

---

draft-ietf-httpbis-digest-headers.md

Add IANA instruction to deprecate the old registry

---

draft-ietf-httpbis-digest-headers.md

- clarify that we are not altering json serialization.

Align example code with the new editorial changes (\n at the end of content).

---

draft-ietf-httpbis-sfbis.md

Be explicit about number return types

---

draft-ietf-httpbis-unprompted-auth.md

Fixes httpwg/http-extensions#2438.

Require unique key material.

---

draft-ietf-httpbis-unprompted-auth.md

Unprompted Auth: add Server Handling section

---

draft-ietf-httpbis-unprompted-auth.md

Add note about linking keys

---

draft-ietf-httpbis-unprompted-auth.md

better intermediaries

---

draft-ietf-httpbis-digest-headers.md

- s/ise-case/use case
- e.g. -> e.g.,
- nit pass

Digest SECDIR review

---

draft-ietf-httpbis-digest-headers.md

- replaces payload with content (except for the changelog)

Replace payload with content.

---

draft-ietf-httpbis-alias-proxy-status.md

Reference structured fields

---

draft-ietf-httpbis-message-signatures.md

Update rules for signature algorithm names

---

draft-ietf-httpbis-digest-headers.md

I tried doing it the way I suggested in #2506 and it wasn't ggod. So I ended up with something closer to what I believe @reschke suggested.
Closes #2506

Editorial clarifications of Appendix A

---

draft-ietf-httpbis-message-signatures.md

message-signatures: remove unused postal adresses

---

draft-ietf-httpbis-message-signatures.md

Import obs-fold, reference US-ASCII, enforce ASCII-ness of Signature Base

message-signatures: clarifications re ASCII-ness of sig base

---

draft-ietf-httpbis-message-signatures.md

message signatures are just one part of an overall system, and this adds language to make that expectation more explicit in the introductory sections.

Describe signatures as a tool in a larger system

---

draft-ietf-httpbis-digest-headers.md

Be more explicit about content processing and trailer

---

draft-ietf-httpbis-alias-proxy-status.md

Add implementation considerations for CNAME chain access

---

draft-ietf-httpbis-message-signatures.md

Encodes query parameter names to match values, to avoid non-ascii or otherwise problematic values.
Closes #2517

Encode query parameter names

---

draft-ietf-httpbis-alias-proxy-status.md

Explain encoding for dots in labels

---

draft-ietf-httpbis-alias-proxy-status.md

Expand dns alias security considerations

---

draft-ietf-httpbis-digest-headers.md

- ballot position feedback #2553

Fix: #2553. Ballot position feedbacks.

---

draft-ietf-httpbis-alias-proxy-status.md

(Parentheticals)

---

draft-ietf-httpbis-digest-headers.md

Be more explicit about validation practices

---

draft-ietf-httpbis-digest-headers.md

Adjust ignored preferences text.

---

draft-ietf-httpbis-alias-proxy-status.md

Closes #2565 
Closes #2563 
Update example domain names to avoid "example-cdn.com" and too-long lines

Update example domains

---

draft-ietf-httpbis-alias-proxy-status.md

IPv6 next hop examples need to be strings

---

draft-ietf-httpbis-sfbis.md

Rough in Display Strings

---

draft-ietf-httpbis-unprompted-auth.md

Add info to context

---

draft-ietf-httpbis-unprompted-auth.md

Avoid issues with signatures that cover any nonce

---

draft-ietf-httpbis-unprompted-auth.md

Contextualize the signature itself

---

draft-ietf-httpbis-digest-headers.md

Remove reserved status and tweak Ref's description

---

draft-ietf-httpbis-digest-headers.md

- consolidates downgrade attacks in security considerations

Consolidate downgrade in sec-

---

draft-ietf-httpbis-resumable-upload.md

Closes https://github.com/httpwg/http-extensions/issues/2500

Replace Upload-Incomplete header with Upload-Complete

---

draft-ietf-httpbis-resumable-upload.md

Closes https://github.com/httpwg/http-extensions/issues/2544
I am not super sure about the wording here, but this is a start. The sentences seem quite long and maybe the rules could also be expressed in fewer words.

Clarify handling of Content-Length and Upload-Complete

---

draft-ietf-httpbis-sfbis.md

Normalize display string % encoding to lowercase.

---

draft-ietf-httpbis-resumable-upload.md

Rough go at moving away from 'procedures'

---

Makefile

This stuff isn't doing anything right now.

Remove some cruft from the Makefile

---

draft-ietf-httpbis-sfbis.md

Add Token caveat

---

draft-ietf-httpbis-resumable-upload.md

Otherwise, aasvg can't detect them.

Fix the corners

---

draft-ietf-httpbis-sfbis.md

Refine security considerations for Display Strings

---

draft-ietf-httpbis-unprompted-auth.md

Unprompted: add public key to context and header

---

draft-ietf-httpbis-unprompted-auth.md

Unprompted: stop using structured fields

---

draft-ietf-httpbis-alias-proxy-status.md

Add example for  encoding`\\`

---

draft-ietf-httpbis-resumable-upload.md

IANA early review highlighted that we were attempting to register to the old table. Lets fix that and do a little more tidyup.

Update resumable uploads IANA considerations

---

draft-ietf-httpbis-safe-method-w-body.xml

Talk about Accept-Query's scope

---

draft-ietf-httpbis-compression-dictionary.md

This removes the hashes negotiation and changes the Available-Dictionary request header to explicitly use sha-256 as discussed in https://github.com/httpwg/http-extensions/issues/2631. If sha-256 becomes insufficient, the hash negotiation can then be added (or different mechanisms can be used).
This is a rebased version of the [original PR](https://github.com/httpwg/http-extensions/pull/2645) (sorry, it got messy so it was cleaner to resubmit a clean one).

Remove hash negotiation and force sha-256

---

draft-ietf-httpbis-alias-proxy-status.md

Downgrade SHOULD to non-normative

---

draft-ietf-httpbis-alias-proxy-status.md

Add POSIX reference for getaddrinfo

---

draft-ietf-httpbis-sfbis.md

Specify unicode encoding failure handling.

---

draft-ietf-httpbis-connect-tcp.md

[connect-tcp] Reword "100 (Continue)" requirement

---

draft-ietf-httpbis-resumable-upload.md

resumable-uploads: Editorial suggestions.

---

draft-ietf-httpbis-connect-tcp.md

[connect-tcp] Note the dependency on Extended CONNECT

---

draft-ietf-httpbis-compression-dictionary.md

Changed it to a proper normative reference.
For #2757

Fixed the URLPattern citations.

---

draft-ietf-httpbis-resumable-upload.md

There were a few cases of the section linking to itself, which I find distracting, so lets remove them.

Remove recursive references

---

draft-ietf-httpbis-unprompted-auth.md

The pieces of my review that I believe will be entirely uncontroversial.

Minor editorial nits

---

draft-ietf-httpbis-unprompted-auth.md

Unprompted: Clarify public key encoding

---

draft-ietf-httpbis-unprompted-auth.md

Unprompted: minor editorial PR

---

draft-ietf-httpbis-unprompted-auth.md

Unprompted: freshness caveats

---

draft-ietf-httpbis-rfc6265bis.md

Updates some out of date portions of the IANA considerations section. 
See #2764 for more info
Closes #2764

Update IANA considerations

---

draft-ietf-httpbis-zstd-window-size.md

Fixes https://github.com/httpwg/http-extensions/issues/2815.

Add "HTTP" to introduction

---

draft-ietf-httpbis-compression-dictionary.md

This addresses the reference issues, comments and nits from the AD review (see #2825)

[compression-dictionary] Fixed references and comments from AD review

---

draft-ietf-httpbis-optimistic-upgrade.md

[optimistic-upgrade] Mention "connect-ip"

---

draft-ietf-httpbis-zstd-window-size.md

Update RFC8878 explicitly

---

draft-ietf-httpbis-zstd-window-size.md

Fixes https://github.com/httpwg/http-extensions/issues/2838.

Add reference to RFC 8878 in IANA registry

---

draft-ietf-httpbis-zstd-window-size.md

Fixes https://github.com/httpwg/http-extensions/issues/2849.

Add note to security considerations

---

draft-ietf-httpbis-rfc6265bis.md

This is a partial revert of 5469d51 from PR #1145

Restore cookie-name = token

---

draft-ietf-httpbis-zstd-window-size.md

As per @evyncke's comment:
> I have only one suggestion: adding the IANA registry URI in the IANA considerations.

Add links to registry URL in the IANA Considerations section

---

draft-ietf-httpbis-unprompted-auth.md

This PR addresses our [responsible AD review](https://lists.w3.org/Archives/Public/ietf-http-wg/2024JulSep/0208.html).

Concealed auth: responsible AD review

---

draft-ietf-httpbis-unprompted-auth.md

Add `Structured Type` column set to `Item` to  IANA registration of `Concealed-Auth-Export` field

concealed IANA review

---

draft-ietf-httpbis-resumable-upload.md

Fix: #2877. Reference RFC9111

---

draft-ietf-httpbis-rfc6265bis.md

Make Service-Workers reference informative

---

draft-ietf-httpbis-resumable-upload.md

- adds more used definitions from HTTP.

Fix: #2875. More HTTP definitions.

---

draft-ietf-httpbis-safe-method-w-body.xml

Mostly editorial, but touches normative text. Fixes #2853.

Reword guidance around URI generation

---

.github/workflows/archive.yml
.github/workflows/ghpages.yml
.github/workflows/publish.yml
.github/workflows/update.yml

These files are going to be out of date very soon.

Update CI files

---

draft-ietf-httpbis-no-vary-search.md

The header field should be registered.

no-vary-search: Fill in IANA Considerations section

---

draft-ietf-httpbis-no-vary-search.md

For most known use cases, a particular resource is consistently invariant to the same query parameters (i.e., either only certain parameters are ever meaningful, or certain parameters are always meaningless).
In such cases, it is possible to avoid searching several stored responses and take a more efficient approach. This shortcut might be desirable in, for example, browser disk cache implementations, where the number of accesses is known to affect cache latency significantly.
Implementations are not required (neither servers nor caches) to take this shortcut; the worst consequence is an avoidable cache miss. Incorrect stored responses are never used.
Resolves #2908.

no-vary-search: Allow more efficient caches by assuming consistency

---

draft-ietf-httpbis-safe-method-w-body.xml

- briefly mentions security advantages
See #1895

Fix: #1895. Mention security advantages.

---

draft-ietf-httpbis-rfc6265bis.md

@reschke, perhaps you have a moment to verify that I've copy/pasted the correct text here?

[RFC6265bis] Updating conformance criteria to match RFC8174.

---

draft-ietf-httpbis-resumable-upload.md

The document incorrectly used the term URL where it should have been URI. This PR corrects this issue and adds a reference to RFC 9110 as a source, [as recommended by Roy Fielding](https://mailarchive.ietf.org/arch/msg/httpbisa/m-iXTJQGdb8XpxGjZWxXGj6Siic/):
> URL is also being used without a reference. For this draft, it
should be URI and reference Section 4 of [HTTP].

Resumable Upload: URI instead of URL

---

draft-ietf-httpbis-resumable-upload.md

This PR attempts to make the text clearer on how the client should react to different status code, especially in which cases it should stop resuming at all, retry the same request or resume the upload by retrieving the offset. Most of this was already implied before, but the explicit mention makes implementing a client easier.
I also merged the text from the dedicated "Redirection" section into the other, corresponding sections.
Currently, the draft is clear that clients should not retry on 4xx, but do so for all 5xx responses. I wonder if this strict rule makes sense, in particular:
- Should the client retry on 408 Request Timeout? The server might have received some representation data and the upload could continue.
- Would it be better if the server didn't resume on 501 Not …

Resumable Upload: Clarify handling of different status codes

---

draft-ietf-httpbis-no-vary-search.md

No-Vary-Search: add an introduction

---

draft-ietf-httpbis-no-vary-search.md

No-Vary-Search: call out parts of Infra used, especially lists

---

README.md

This is a custom README, so it can use this new flag.

Disable regeneration of the README

---

draft-ietf-httpbis-optimistic-upgrade.md

[connect-tcp] Optimism is safe with Connection:close

---

draft-ietf-httpbis-safe-method-w-body.xml

Reverts httpwg/http-extensions#3080

Revert "query: some editorial nits"

---

draft-ietf-httpbis-optimistic-upgrade.md

[optimistic-upgrade] Clarify connect-udp update

---

draft-ietf-httpbis-optimistic-upgrade.md

Based on suggestion from Martin Thomson

[optimistic-upgrade] Recommend empty bodies in Upgrade request

---

draft-ietf-httpbis-rfc6265bis.md

Update Steven Bingler's editor information

6265bis: Update editor info

---

draft-ietf-httpbis-incremental.md

Thanks to @bemasc who suggested that this field might be a signal to endpoint software.

Disable buffering in endpoints too

---

draft-ietf-httpbis-rfc6265bis.md

This PR address the remaining technical issues from the [Gen-ART review](https://lists.w3.org/Archives/Public/ietf-http-wg/2025JanMar/0124.html).

Gen-ART review - Address technical issues

---

draft-ietf-httpbis-layered-cookies.md

Fixes #2531.
See https://github.com/httpwg/http-extensions/issues/2531#issuecomment-3182101585 for justification.

Remove Max-Age compat note

---

draft-ietf-httpbis-resumable-upload.md

State very clearly examples are illustrative and non-normative

---

draft-ietf-httpbis-resumable-upload.md

Increase upload and append sizes to the 100 MB range

---

draft-ietf-httpbis-rfc6265bis.md

Addresses issues brought up during the Secdir review https://lists.w3.org/Archives/Public/ietf-http-wg/2025JanMar/0125.html

RFC6265bis: Address Secdir nits

---

draft-ietf-httpbis-resumable-upload.md

Several typo and spelling fixes

---

draft-ietf-httpbis-resumable-upload.md

s/not the/was not

---

draft-ietf-httpbis-no-vary-search.md

I think I managed to find everyone who contributed to discussions on this repo, in https://github.com/jeremyroman/http-no-vary-search/issues?q=is%3Aissue%20state%3Aclosed, and in https://github.com/WICG/nav-speculation/issues?q=is%3Aissue%20state%3Aclosed%20label%3Ano-vary-search.

No-Vary-Search: add acknowledgments

---

draft-ietf-httpbis-resumable-upload.md

Use unique URLs for different examples

---

draft-ietf-httpbis-safe-method-w-body.xml

(supercedes #3259 due to a lost fight with git, sorry)

QUERY: caching - mention GET alternative wrt caching (addresses #3120)
